coverage:
  precision: 2
  range: "50...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%  # Ensure PRs maintain good coverage
        threshold: 2%

  ignore:
    - "tests/*"       # Ignore test files in coverage calculation
    - "examples/*"    # Ignore example scripts
    - "setup.py"      # Ignore setup scripts
    - "docs/*"        # Ignore documentation

fixes:
  # Replace absolute paths with relative paths in Codecov
  - "s|/home/runner/work/biotuner/biotuner|.|g"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true  # Only comment if coverage changes

parsers:
  python:
    include_branch: true  # Ensure branch coverage is tracked

flags:
  unit:
    paths:
      - "biotuner/"
    carryforward: true  # Preserve previous coverage data for unchanged files
