"""
Tuning export service.

Emits Scala (.scl) and a few simple sibling formats from a list of ratios.
The expected input is a list of float ratios (e.g. 1.0, 1.125, ...). The
ratios are typically already octave-reduced to [1, 2], but this service does
not enforce that.
"""

from __future__ import annotations

import json
import math
from io import BytesIO
from typing import Iterable, List


def _ratios_to_cents(ratios: Iterable[float]) -> List[float]:
    out = []
    for r in ratios:
        if r is None or r <= 0:
            continue
        out.append(1200.0 * math.log2(float(r)))
    return out


def to_scl(tuning_ratios: List[float], description: str = "Biotuner-derived tuning",
           filename: str = "biotuner_tuning") -> bytes:
    """
    Emit a Scala .scl file.

    Per Scala spec:
      - First line: a "!" comment line with the filename
      - One free-form description line
      - Number of notes
      - One pitch per line; either as cents (decimal with a period, e.g. "204.0")
        or as a ratio (e.g. "3/2"). We emit cents for non-octave entries and
        "2/1" for the closing octave.
    """
    description = (description or "Biotuner-derived tuning").strip().replace("\n", " ")
    # Skip the unison if present at the start; Scala excludes 1/1.
    ratios = [r for r in tuning_ratios if r and r > 0]
    if ratios and abs(ratios[0] - 1.0) < 1e-9:
        ratios = ratios[1:]

    # Always close on the octave if not already there.
    has_octave = ratios and abs(ratios[-1] - 2.0) < 1e-6
    if not has_octave:
        ratios = list(ratios) + [2.0]

    n_notes = len(ratios)
    cents = _ratios_to_cents(ratios)

    lines = []
    lines.append(f"! {filename}.scl")
    lines.append("!")
    lines.append(description)
    lines.append(f" {n_notes}")
    lines.append("!")
    for r, c in zip(ratios, cents):
        if abs(r - 2.0) < 1e-9:
            lines.append(" 2/1")
        else:
            lines.append(f" {c:.4f}")

    return ("\n".join(lines) + "\n").encode("utf-8")


def to_txt(tuning_ratios: List[float], description: str = "Biotuner-derived tuning",
           filename: str = "biotuner_tuning") -> bytes:
    """Plain-text dump: one ratio per line with cents in a comment."""
    lines = [f"# {filename}", f"# {description}", "# ratio\tcents"]
    for r in tuning_ratios:
        if r is None or r <= 0:
            continue
        c = 1200.0 * math.log2(float(r))
        lines.append(f"{r:.6f}\t{c:.4f}")
    return ("\n".join(lines) + "\n").encode("utf-8")


def to_tun(tuning_ratios: List[float], description: str = "Biotuner-derived tuning",
           filename: str = "biotuner_tuning",
           base_freq: float = 8.1757989156) -> bytes:
    """
    Minimal AnaMark .tun file. Maps tuning ratios across 128 MIDI notes
    cyclically; for many DAWs this is enough to load and use.

    base_freq defaults to MIDI 0 = C-1 (~8.1758 Hz).
    """
    ratios = [r for r in tuning_ratios if r and r > 0]
    if not ratios:
        ratios = [1.0]
    # Build 128 frequencies by repeating the tuning over octaves
    has_octave = abs(ratios[-1] - 2.0) < 1e-6
    if not has_octave:
        ratios = ratios + [2.0]
    octave_size = len(ratios) - 1  # ratios includes 2/1 as boundary

    lines = []
    lines.append("; .tun file generated by Biotuner")
    lines.append(f"; {description}")
    lines.append("[Tuning]")
    for midi in range(128):
        oct_index, step = divmod(midi, octave_size)
        ratio = (2 ** oct_index) * ratios[step]
        freq = base_freq * ratio
        cents = 1200.0 * math.log2(freq / base_freq) if freq > 0 else 0.0
        lines.append(f"Note {midi} = {cents:.4f}")

    return ("\n".join(lines) + "\n").encode("utf-8")


def to_json(tuning_ratios: List[float], description: str = "Biotuner-derived tuning",
            filename: str = "biotuner_tuning") -> bytes:
    payload = {
        "name": filename,
        "description": description,
        "ratios": [float(r) for r in tuning_ratios if r and r > 0],
        "cents": _ratios_to_cents([r for r in tuning_ratios if r and r > 0]),
    }
    return json.dumps(payload, indent=2).encode("utf-8")


EXPORTERS = {
    "scl":  (to_scl,  "application/octet-stream"),
    "tun":  (to_tun,  "application/octet-stream"),
    "txt":  (to_txt,  "text/plain"),
    "json": (to_json, "application/json"),
}


def export(format: str, tuning_ratios: List[float], description: str,
           filename: str) -> tuple[bytes, str]:
    fmt = format.lower()
    if fmt not in EXPORTERS:
        raise ValueError(f"Unsupported export format: {format}")
    fn, mime = EXPORTERS[fmt]
    data = fn(tuning_ratios, description=description, filename=filename)
    return data, mime
