"""biotuner.mos — moment-of-symmetry scales, from Stern-Brocot to biosignal.

A *moment of symmetry* (equivalently, a *well-formed*) scale is generated by
stacking a single interval and has exactly two step sizes, distributed as
evenly as two sizes can be.  Almost every scale anyone actually plays is one:
the pentatonic, the diatonic, the chromatic, and a large microtonal hinterland
that ordinary keyboards cannot reach.

This package implements Milne, Carlé, Sethares, Noll & Holland (2011),
*Scratching the Scale Labyrinth* (LNAI 6726, 180--195) -- the combinatorics,
the visualisation, the modal algebra, the performance technique, and the
timbre matching -- and adds the piece the paper does not have: fitting these
scales to a biosignal.

Quick start
-----------
>>> from biotuner.mos import mos, fit_mos, plot_labyrinth
>>> d = mos(3 / 2, 7)                       # stack fifths, take seven notes
>>> d.signature, d.word
('5L2s', 'LLLsLLs')
>>> print(d.summary())                      # doctest: +ELLIPSIS
5L2s  (7 notes)   LLLsLLs
...
>>> fit = fit_mos([1.0, 1.13, 1.26, 1.34, 1.49])[0]   # which scale is this signal in?
>>> fit.signature                                     # doctest: +SKIP
'4L3s'

Layers
------
- :mod:`~biotuner.mos.theory`        Stern-Brocot, landmarks, Christoffel words
  (standard library only)
- :mod:`~biotuner.mos.scale`         :class:`MOSScale`, the central object
- :mod:`~biotuner.mos.modes`         modes, brightness, the ℤ² height--width lattice
- :mod:`~biotuner.mos.metrics`       Myhill, propriety, evenness, JI error
- :mod:`~biotuner.mos.temperaments`  commas → rank-2 mappings → optimal generators
- :mod:`~biotuner.mos.derive`        **biosignal → MOS**: fitting and trajectories
- :mod:`~biotuner.mos.fourier`       Fourier Scratching play states
- :mod:`~biotuner.mos.timbre`        Dynamic Tonality partial matching
- :mod:`~biotuner.mos.plotting`      the labyrinth and friends, in matplotlib
- :mod:`~biotuner.mos.labyrinths`    other labyrinths: ?(g) and depth coordinates,
  noble/metallic trees, the Farey tessellation on the Poincare disk
- :mod:`~biotuner.mos.ternary`       three step sizes, where the labyrinth becomes a simplex
- :mod:`~biotuner.mos.morph`         moving between scales: three ways through the labyrinth
- :mod:`~biotuner.mos.interactive`   Plotly and ipywidgets explorers (optional deps)
- :mod:`~biotuner.mos.design`        scales as figures: star polygons, interval webs
- :mod:`~biotuner.mos.legacy`        the pre-replacement figures, frozen for comparison

Relation to ``scale_construction``
----------------------------------
The older MOS helpers in :mod:`biotuner.scale_construction` (``find_MOS``,
``tuning_MOS_info``, ``Stern_Brocot``, ``tuning_range_to_MOS``) still work
unchanged.  They brute-force what this package derives exactly, and several of
them silently assume a 2/1 period.  :func:`~biotuner.mos.scale.mos_family` is
the direct replacement for ``find_MOS``.
"""

from biotuner.mos import (
    derive,
    design,
    labyrinths,
    legacy,
    metrics,
    modes,
    morph,
    plotting,
    scale,
    temperaments,
    ternary,
    theory,
)

# --- theory: the exact combinatorics ------------------------------------- #
from biotuner.mos.theory import (
    PERIOD_CENTS,
    Landmarks,
    SBNode,
    christoffel_word,
    coherence_range,
    common_tones,
    continued_fraction,
    convergents_from_cf,
    degrees_from_generator,
    embedding,
    farey_sequence,
    fold_generator,
    fraction_to_generator,
    generator_fraction,
    is_farey_neighbor,
    mediant,
    mos_cardinalities,
    mos_landmarks,
    mos_series,
    mos_signature,
    mos_word,
    noble_mediant,
    sb_node_at,
    sb_path,
    sb_tree_nodes,
    sb_walk,
    semiconvergents,
    signature_brackets,
    signature_ranges,
    step_sizes,
    word_from_generator,
)

# --- the scale object ----------------------------------------------------- #
from biotuner.mos.scale import MOSScale, mos, mos_family

# --- modes ---------------------------------------------------------------- #
from biotuner.mos.modes import (
    DIATONIC_MODE_NAMES,
    Mode,
    chain_order,
    christoffel_mode,
    mode_lattice,
    mode_names,
    parsimony_chain,
    stacking_brightens,
    wf_number,
)

# --- metrics -------------------------------------------------------------- #
from biotuner.mos.metrics import (
    MODEL_PARAMETERS,
    MOSness,
    blackwood_r,
    degree_signatures,
    evenness,
    generic_interval_sizes,
    harmonicity,
    has_unique_degree_signatures,
    interval_matrix,
    is_proper,
    ji_error,
    mos_ness,
    mos_report,
    myhill_property,
)

# --- temperaments --------------------------------------------------------- #
from biotuner.mos.temperaments import (
    PRIMES_5,
    PRIMES_7,
    TEMPERAMENTS,
    Rank2Temperament,
    all_temperaments,
    hermite_normal_form,
    monzo,
    nearest_temperaments,
    rank2_from_comma,
    saturated_annihilator,
    temperament,
)

# --- biosignal -> MOS ----------------------------------------------------- #
from biotuner.mos.derive import (
    FOLD_TOLERANCE_CENTS,
    GENERATOR_EPSILON,
    MIN_REFINED_STEP,
    FitField,
    ForwardScale,
    MOSFit,
    best_mos,
    compare_sources,
    explain_fit,
    fit_field,
    fit_mos,
    forward_scales,
    generator_candidates,
    labyrinth_positions,
    mos_from_biotuner,
    mos_trajectory,
    mos_tuning,
    trajectory_dataframe,
    trajectory_from_windows,
)

# --- plotting ------------------------------------------------------------- #
from biotuner.mos.plotting import (
    plot_fit_field,
    plot_forward_vs_inverse,
    plot_ji_landscape,
    plot_labyrinth,
    plot_mode_lattice,
    plot_modes,
    plot_mos_family,
    plot_mos_fit,
    plot_mos_trajectory,
    plot_play_state,
    plot_scale_wheel,
    plot_stern_brocot,
    plot_step_covariation,
)

# ``fourier`` and ``timbre`` import numpy only, so they are safe to pull in
# eagerly; ``interactive`` needs plotly/ipywidgets and is left to the caller.
from biotuner.mos import fourier, timbre
from biotuner.mos.fourier import (
    NoteEvent,
    PlayState,
    keyboard_sectors,
    partial,
    phase_to_degree,
    scratch_sequence,
    to_events,
    to_frequencies,
)
from biotuner.mos.timbre import (
    PartialMap,
    SimpleTimbre,
    dissonance_advantage,
    dynamic_timbre,
    map_harmonic,
    matched_partials,
    matched_ratios,
    matched_spectrum,
    scale_dissonance,
    spectral_dissonance,
)


# --- alternative labyrinths ---------------------------------------------- #
from biotuner.mos.labyrinths import (
    MEDIANT,
    METALLIC_MEANS,
    METALLIC_NAMES,
    NOBLE,
    PHI,
    TreeRule,
    VariantNode,
    metallic,
    minkowski_q,
    plot_farey_tessellation,
    plot_labyrinth_variant,
    variant_tree,
    variant_walk,
    weighted,
)

# --- three step sizes: the ternary simplex -------------------------------- #
from biotuner.mos.ternary import (
    TernaryScale,
    barycentric_to_xy,
    mos_substitution,
    plot_ternary_atlas,
    plot_ternary_simplex,
    proper_fraction,
    sampled_max_variety,
    ternary_atlas,
    ternary_words,
)

# --- moving between scales ------------------------------------------------ #
# ``morph.morph`` -- the strategy dispatcher -- is deliberately *not* lifted to
# the package namespace: it would shadow the submodule, and
# ``from biotuner.mos import morph`` giving back a function rather than the
# module it names is the kind of surprise that costs an afternoon.  Reach it as
# ``mos.morph.morph``, or name the strategy you want directly.
from biotuner.mos.morph import (
    STRATEGIES as MORPH_STRATEGIES,
    Morph,
    MorphStep,
    animate_morph,
    morph_audio,
    plot_morph_comparison,
    plot_morph_filmstrip,
    plot_morph_path,
    plot_morph_trajectory,
    signature_children,
    signature_parent,
    signature_route,
    tree_morph,
    tuning_morph,
    voice_morph,
)

# --- scales as figures ---------------------------------------------------- #
from biotuner.mos.design import (
    PALETTES,
    STYLES,
    WebGeometry,
    plot_scale_web,
    plot_web_gallery,
    star_density,
    star_hop,
    web_geometry,
)

# ``interactive`` is safe to import eagerly: plotly and ipywidgets are pulled
# in per-call by its ``_require`` helper, never at module load, so importing it
# here costs nothing on a machine without them.
from biotuner.mos import interactive
from biotuner.mos.interactive import (
    dissonance_explorer,
    fit_explorer,
    labyrinth_plotly,
    matrix_explorer,
    morph_explorer,
    mos_explorer,
    scratch_explorer,
    simplex_explorer,
    trajectory_explorer,
    web_explorer,
)

__all__ = [
    # submodules
    "theory", "scale", "modes", "metrics", "temperaments", "derive",
    "fourier", "timbre", "plotting", "interactive", "labyrinths", "ternary",
    "legacy", "design", "morph",
    # theory
    "PERIOD_CENTS", "Landmarks", "SBNode", "christoffel_word", "coherence_range", "common_tones",
    "continued_fraction", "convergents_from_cf", "degrees_from_generator",
    "embedding", "farey_sequence", "fold_generator", "fraction_to_generator",
    "generator_fraction", "is_farey_neighbor", "mediant", "mos_cardinalities",
    "mos_landmarks", "mos_series", "mos_signature", "mos_word", "noble_mediant",
    "sb_node_at", "sb_path", "sb_tree_nodes", "sb_walk", "semiconvergents",
    "signature_brackets", "signature_ranges", "step_sizes", "word_from_generator",
    # scale + modes
    "MOSScale", "mos", "mos_family",
    "Mode", "DIATONIC_MODE_NAMES", "chain_order", "christoffel_mode",
    "mode_lattice", "mode_names", "parsimony_chain", "stacking_brightens",
    "wf_number",
    # metrics
    "blackwood_r", "degree_signatures", "evenness", "generic_interval_sizes",
    "harmonicity", "has_unique_degree_signatures", "interval_matrix", "is_proper",
    "ji_error", "mos_report", "myhill_property",
    "MODEL_PARAMETERS", "MOSness", "mos_ness",
    # temperaments
    "PRIMES_5", "PRIMES_7", "TEMPERAMENTS", "Rank2Temperament", "all_temperaments",
    "monzo", "nearest_temperaments", "rank2_from_comma", "temperament",
    "saturated_annihilator", "hermite_normal_form",
    # derive
    "MOSFit", "FitField", "ForwardScale", "fit_field", "best_mos", "explain_fit",
    "fit_mos", "forward_scales",
    "generator_candidates", "FOLD_TOLERANCE_CENTS", "GENERATOR_EPSILON",
    "MIN_REFINED_STEP", "compare_sources",
    "labyrinth_positions", "mos_from_biotuner", "mos_trajectory", "mos_tuning",
    "trajectory_dataframe", "trajectory_from_windows",
    # fourier + timbre
    "PlayState", "NoteEvent", "partial", "keyboard_sectors", "phase_to_degree",
    "scratch_sequence", "to_events", "to_frequencies",
    "PartialMap", "SimpleTimbre", "dissonance_advantage", "dynamic_timbre", "map_harmonic",
    "matched_partials", "matched_ratios", "matched_spectrum", "scale_dissonance",
    "spectral_dissonance",
    # plotting
    "plot_fit_field", "plot_forward_vs_inverse", "plot_ji_landscape",
    "plot_labyrinth", "plot_mode_lattice", "plot_modes",
    "plot_mos_family", "plot_mos_fit", "plot_mos_trajectory", "plot_play_state",
    "plot_scale_wheel", "plot_stern_brocot", "plot_step_covariation",
    # interactive
    "labyrinth_plotly", "mos_explorer", "fit_explorer", "scratch_explorer",
    "web_explorer", "simplex_explorer", "trajectory_explorer",
    "dissonance_explorer", "matrix_explorer", "morph_explorer",
    # moving between scales
    "MORPH_STRATEGIES", "Morph", "MorphStep", "tuning_morph",
    "tree_morph", "voice_morph", "signature_children", "signature_parent",
    "signature_route", "morph_audio", "animate_morph", "plot_morph_path",
    "plot_morph_trajectory", "plot_morph_filmstrip", "plot_morph_comparison",
    # scales as figures
    "STYLES", "PALETTES", "WebGeometry", "web_geometry", "star_density",
    "star_hop",
    "plot_scale_web", "plot_web_gallery",
    # alternative labyrinths
    "minkowski_q", "PHI", "TreeRule", "MEDIANT", "NOBLE", "metallic", "weighted",
    "METALLIC_MEANS", "METALLIC_NAMES", "VariantNode", "variant_tree",
    "variant_walk", "plot_labyrinth_variant", "plot_farey_tessellation",
    # ternary
    "TernaryScale", "ternary_words", "sampled_max_variety", "ternary_atlas",
    "mos_substitution", "proper_fraction", "barycentric_to_xy",
    "plot_ternary_simplex", "plot_ternary_atlas",
]
