"""Number theory of moment-of-symmetry (well-formed) scales.

This module is deliberately dependency-free -- it imports nothing but the
standard library, so its correctness can be checked in isolation from the
rest of biotuner.  Everything here works on exact :class:`~fractions.Fraction`
arithmetic; no floating-point comparison decides a combinatorial fact.

The central object of study is the **generator fraction**

.. math::  g = \\log(\\text{generator}) / \\log(\\text{period}) \\in (0, 1)

i.e. the size of the generator expressed as a fraction of the period
(the "generator/period tuning ratio" of Milne et al., 2011).  A generator of
702 cents against a 1200-cent period gives :math:`g = 0.585`.

The key fact, due to the three-distance theorem and exploited throughout
Milne et al. §3, is that stacking a generator produces a scale with exactly
two step sizes **precisely** at the cardinalities that appear as denominators
along the Stern-Brocot path toward :math:`g`.  So the entire MOS series of a
generator is obtained by walking the tree -- no brute-force search over
cardinalities is needed.

References
----------
Milne, A.J., Carlé, M., Sethares, W.A., Noll, T., Holland, S. (2011).
Scratching the Scale Labyrinth. In *Mathematics and Computation in Music*,
LNAI 6726, 180--195. https://doi.org/10.1007/978-3-642-21590-2_14

Carey, N., Clampitt, D. (1989). Aspects of Well-formed Scales.
*Music Theory Spectrum* 11, 187--206.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from fractions import Fraction
from typing import Iterator, List, Optional, Sequence, Tuple

__all__ = [
    "mediant",
    "noble_mediant",
    "is_farey_neighbor",
    "farey_sequence",
    "continued_fraction",
    "convergents_from_cf",
    "semiconvergents",
    "SBNode",
    "sb_walk",
    "sb_path",
    "sb_node_at",
    "sb_tree_nodes",
    "mos_cardinalities",
    "mos_signature",
    "mos_series",
    "signature_brackets",
    "signature_ranges",
    "Landmarks",
    "mos_landmarks",
    "embedding",
    "coherence_range",
    "mos_word",
    "christoffel_word",
    "word_from_generator",
    "generator_fraction",
    "fraction_to_generator",
    "fold_generator",
    "common_tones",
    "step_sizes",
    "degrees_from_generator",
    "PERIOD_CENTS",
]

#: Cents in a 2/1 period.  Used only for cents conversions, never for logic.
PERIOD_CENTS = 1200.0

_ZERO = Fraction(0, 1)
_ONE = Fraction(1, 1)


# --------------------------------------------------------------------------- #
# Farey / Stern-Brocot primitives
# --------------------------------------------------------------------------- #
def mediant(x: Fraction, y: Fraction) -> Fraction:
    """The mediant ``(a+c)/(b+d)`` of ``a/b`` and ``c/d``.

    Note this is *not* the same as ``(x + y) / 2``; the mediant depends on the
    representation, which is why both arguments must already be in lowest
    terms (``Fraction`` guarantees that).

    Examples
    --------
    >>> mediant(Fraction(1, 2), Fraction(3, 5))
    Fraction(4, 7)
    """
    return Fraction(
        x.numerator + y.numerator, x.denominator + y.denominator
    )


def noble_mediant(x: Fraction, y: Fraction) -> float:
    """The φ-weighted "noble" mediant ``(a + cφ) / (b + dφ)``.

    This is the point in ``(x, y)`` that is *maximally far* from every simple
    rational -- the limit of the infinite Stern-Brocot path ``LRLRLR…``.  In
    MOS terms it is the generator whose scale never settles into an equal
    temperament, and so keeps producing new MOS cardinalities forever.

    Examples
    --------
    >>> round(noble_mediant(Fraction(1, 2), Fraction(3, 5)), 6)
    0.580179
    """
    phi = (1.0 + 5.0**0.5) / 2.0
    num = x.numerator + y.numerator * phi
    den = x.denominator + y.denominator * phi
    return num / den


def is_farey_neighbor(x: Fraction, y: Fraction) -> bool:
    """True when ``|ad - bc| == 1``, i.e. ``x`` and ``y`` bracket a tree node.

    Every bracketing pair produced by :func:`sb_walk` satisfies this, and it
    is what makes the mediant land in lowest terms.
    """
    return (
        abs(x.numerator * y.denominator - x.denominator * y.numerator) == 1
    )


def farey_sequence(n: int) -> List[Fraction]:
    """The Farey sequence ``F_n``: every reduced ``p/q`` in ``[0, 1]`` with ``q <= n``.

    Generated by the standard next-term recurrence, so this is ``O(len(F_n))``
    rather than ``O(n^2)``.  The loop stops once the recurrence steps past
    ``1/1``, which is the sequence's last term.

    Examples
    --------
    >>> farey_sequence(5)  # doctest: +NORMALIZE_WHITESPACE
    [Fraction(0, 1), Fraction(1, 5), Fraction(1, 4), Fraction(1, 3),
     Fraction(2, 5), Fraction(1, 2), Fraction(3, 5), Fraction(2, 3),
     Fraction(3, 4), Fraction(4, 5), Fraction(1, 1)]
    """
    if n < 1:
        raise ValueError(f"n must be >= 1, got {n!r}")
    out = [Fraction(0, 1)]
    a, b, c, d = 0, 1, 1, n
    while c <= n:
        out.append(Fraction(c, d))
        k = (n + b) // d
        a, b, c, d = c, d, k * c - a, k * d - b
    return out


def continued_fraction(x: float, max_terms: int = 32, tol: float = 1e-13) -> List[int]:
    """Simple continued-fraction expansion ``[a0; a1, a2, …]`` of ``x``.

    Terminates early once the remaining fractional part falls below ``tol``,
    which keeps a rational input from producing spurious huge terms from
    floating-point noise.
    """
    terms: List[int] = []
    v = float(x)
    for _ in range(max_terms):
        a = math.floor(v)
        terms.append(int(a))
        frac = v - a
        if frac < tol:
            break
        v = 1.0 / frac
    return terms


def convergents_from_cf(cf: Sequence[int]) -> List[Fraction]:
    """Convergents of a continued fraction, in order.

    Examples
    --------
    The fifth's convergents run through the historically important divisions
    of the octave:

    >>> convergents_from_cf(continued_fraction(math.log2(3 / 2), 6))
    [Fraction(0, 1), Fraction(1, 1), Fraction(1, 2), Fraction(3, 5), Fraction(7, 12), Fraction(24, 41)]
    """
    out: List[Fraction] = []
    h_prev, h = 0, 1  # numerators   h_{-2}, h_{-1}
    k_prev, k = 1, 0  # denominators k_{-2}, k_{-1}
    for a in cf:
        h_prev, h = h, a * h + h_prev
        k_prev, k = k, a * k + k_prev
        out.append(Fraction(h, k))
    return out


def semiconvergents(x: float, max_denominator: int = 53) -> List[Fraction]:
    """Every semiconvergent of ``x`` with denominator ``<= max_denominator``.

    The semiconvergents are exactly the Stern-Brocot nodes on the path toward
    ``x``, so their denominators are exactly the MOS cardinalities of a
    generator fraction ``x`` (see :func:`mos_cardinalities`).  Provided as a
    standalone entry point because it is the classical name for the object.
    """
    return [node.node for node in sb_walk(x, max_cardinality=max_denominator)]


# --------------------------------------------------------------------------- #
# The Stern-Brocot walk
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class SBNode:
    """One node on the Stern-Brocot path toward a generator fraction.

    Attributes
    ----------
    left, right : Fraction
        The bracketing Farey pair, ``left < right``, with ``|ad - bc| == 1``.
    node : Fraction
        Their mediant.  Represents an equal division of the period into
        ``node.denominator`` steps.
    depth : int
        Number of tree levels descended, ``0`` for the first node (``1/2``).
    turn : str
        ``'L'`` or ``'R'`` -- the branch taken *to reach* this node, ``''``
        for the root.
    exact : bool
        True when the target generator equals ``node`` exactly.  The scale is
        then that equal temperament: its large and small steps coincide, and
        no further MOS exist.
    """

    left: Fraction
    right: Fraction
    node: Fraction
    depth: int
    turn: str
    exact: bool

    @property
    def cardinality(self) -> int:
        """Number of notes in the MOS whose range this node bounds."""
        return self.node.denominator

    def signature(self, g: float) -> Tuple[int, int]:
        """``(n_large, n_small)`` of the MOS at this cardinality for generator ``g``.

        Milne et al. §3: for bracket ``a/b, c/d`` with mediant ``m``, the
        sub-range ``(a/b, m)`` hosts ``b`` large and ``d`` small steps, and
        ``(m, c/d)`` hosts ``d`` large and ``b`` small.
        """
        b = self.left.denominator
        d = self.right.denominator
        if self.exact or g == float(self.node):
            # Degenerate: L and s are the same size.  Report the sub-range
            # counts on the side the walk was heading, by convention (b, d).
            return (b, d)
        return (b, d) if g < float(self.node) else (d, b)


def sb_walk(
    g: float,
    max_cardinality: int = 53,
    max_depth: int = 512,
) -> Iterator[SBNode]:
    """Walk the Stern-Brocot tree from ``0/1``–``1/1`` toward ``g``.

    Each yielded node's denominator is an MOS cardinality of the generator,
    and the node itself is the equal temperament at which that MOS's large and
    small steps become equal.  The walk stops when the mediant's denominator
    would exceed ``max_cardinality``, or when ``g`` is hit exactly.

    Parameters
    ----------
    g : float
        Generator fraction in ``(0, 1)``.  Use :func:`generator_fraction` to
        obtain one from a frequency ratio.
    max_cardinality : int, default 53
        Stop once the next node would have more notes than this.
    max_depth : int, default 512
        Hard recursion guard; only reachable for pathological inputs.

    Yields
    ------
    SBNode

    Examples
    --------
    The perfect fifth generates the familiar Pythagorean series:

    >>> g = math.log2(3 / 2)
    >>> [n.cardinality for n in sb_walk(g, max_cardinality=53)]
    [2, 3, 5, 7, 12, 17, 29, 41, 53]
    """
    if not 0.0 < g < 1.0:
        raise ValueError(
            f"generator fraction must lie strictly in (0, 1), got {g!r}. "
            "Use fold_generator() or generator_fraction() first."
        )
    if max_cardinality < 2:
        return

    lo, hi = _ZERO, _ONE
    depth = 0
    turn = ""
    while depth < max_depth:
        m = mediant(lo, hi)
        if m.denominator > max_cardinality:
            return
        exact = g == float(m)
        yield SBNode(left=lo, right=hi, node=m, depth=depth, turn=turn, exact=exact)
        if exact:
            return
        if g < float(m):
            hi, turn = m, "L"
        else:
            lo, turn = m, "R"
        depth += 1


def sb_path(g: float, max_cardinality: int = 53) -> str:
    """The ``'L'``/``'R'`` turn sequence of the walk toward ``g``.

    A compact fingerprint of where a generator sits in the labyrinth.  One
    shorter than the number of nodes visited, since the root ``1/2`` is
    reached without a turn.

    Examples
    --------
    >>> sb_path(math.log2(3 / 2), max_cardinality=12)
    'RLLR'
    """
    return "".join(n.turn for n in sb_walk(g, max_cardinality=max_cardinality))


def sb_node_at(g: float, cardinality: int) -> Optional[SBNode]:
    """The node of ``g``'s walk with the given cardinality, or ``None``.

    ``None`` means ``cardinality`` is not an MOS cardinality of ``g``.
    """
    for node in sb_walk(g, max_cardinality=cardinality):
        if node.cardinality == cardinality:
            return node
    return None


def sb_tree_nodes(max_cardinality: int = 12) -> List[SBNode]:
    """Every Stern-Brocot node in ``(0, 1)`` with denominator ``<= max_cardinality``.

    Unlike :func:`sb_walk`, which follows one generator, this enumerates the
    whole tree -- the data behind the labyrinth drawing.  Each node carries its
    own bracketing pair, so the arc endpoints and landmark tunings of every MOS
    are available directly.

    Returned in breadth-first order (shallowest first), which is also the order
    the labyrinth's rings fill in.
    """
    if max_cardinality < 2:
        return []
    out: List[SBNode] = []
    # (left, right, depth, turn)
    frontier: List[Tuple[Fraction, Fraction, int, str]] = [(_ZERO, _ONE, 0, "")]
    while frontier:
        nxt: List[Tuple[Fraction, Fraction, int, str]] = []
        for lo, hi, depth, turn in frontier:
            m = mediant(lo, hi)
            if m.denominator > max_cardinality:
                continue
            out.append(
                SBNode(left=lo, right=hi, node=m, depth=depth, turn=turn, exact=False)
            )
            nxt.append((lo, m, depth + 1, "L"))
            nxt.append((m, hi, depth + 1, "R"))
        frontier = nxt
    return out


# --------------------------------------------------------------------------- #
# MOS series of a generator
# --------------------------------------------------------------------------- #
def mos_cardinalities(
    g: float, max_cardinality: int = 53, include_trivial: bool = False
) -> List[int]:
    """Cardinalities at which stacking ``g`` yields exactly two step sizes.

    Parameters
    ----------
    g : float
        Generator fraction in ``(0, 1)``.
    max_cardinality : int, default 53
        Largest scale size to report.
    include_trivial : bool, default False
        Whether to include cardinality 2 (a single generator plus the root),
        which is an MOS but a musically empty one.

    Examples
    --------
    Milne et al. §2 quote both of these series:

    >>> mos_cardinalities(math.log2(3 / 2), 53, include_trivial=True)
    [2, 3, 5, 7, 12, 17, 29, 41, 53]
    >>> mos_cardinalities(316 / 1200, 19, include_trivial=True)
    [2, 3, 4, 7, 11, 15, 19]
    """
    cards = [n.cardinality for n in sb_walk(g, max_cardinality=max_cardinality)]
    if not include_trivial:
        cards = [c for c in cards if c > 2]
    return cards


def mos_signature(g: float, cardinality: int) -> Tuple[int, int]:
    """``(n_large, n_small)`` of the ``cardinality``-note MOS generated by ``g``.

    Raises
    ------
    ValueError
        If ``cardinality`` is not an MOS cardinality of ``g``.

    Examples
    --------
    >>> mos_signature(math.log2(3 / 2), 7)
    (5, 2)
    >>> mos_signature(math.log2(3 / 2), 12)
    (5, 7)
    """
    node = sb_node_at(g, cardinality)
    if node is None:
        raise ValueError(
            f"{cardinality} is not an MOS cardinality of generator fraction "
            f"{g!r}; available up to {cardinality}: "
            f"{mos_cardinalities(g, cardinality, include_trivial=True)}"
        )
    return node.signature(g)


def mos_series(
    g: float, max_cardinality: int = 53, include_trivial: bool = False
) -> List[Tuple[int, int, int]]:
    """``(cardinality, n_large, n_small)`` for every MOS of ``g``.

    Examples
    --------
    >>> mos_series(math.log2(3 / 2), 12)
    [(3, 2, 1), (5, 2, 3), (7, 5, 2), (12, 5, 7)]
    """
    out = []
    for node in sb_walk(g, max_cardinality=max_cardinality):
        if not include_trivial and node.cardinality <= 2:
            continue
        n_large, n_small = node.signature(g)
        out.append((node.cardinality, n_large, n_small))
    return out


# --------------------------------------------------------------------------- #
# From a signature back to the tree
# --------------------------------------------------------------------------- #
def _solve_bracket(b: int, d: int) -> Tuple[Fraction, Fraction]:
    """Farey pair ``(a/b, c/d)`` in ``[0, 1]`` with ``b*c - a*d == 1``.

    Exactly one solution has ``0 <= a < b``; the modular inverse pins it down.
    """
    if math.gcd(b, d) != 1:
        raise ValueError(
            f"a MOS signature must be co-prime (Milne et al. §2); got "
            f"gcd({b}, {d}) = {math.gcd(b, d)}"
        )
    if b == 1:
        # b*c - a*d = 1 with a = 0 gives c = 1.
        return Fraction(0, 1), Fraction(1, d)
    # b*c ≡ 1 (mod d)  ->  c ≡ b^{-1} (mod d); then a = (b*c - 1) / d.
    if d == 1:
        c = 1
        a = b - 1
        return Fraction(a, b), Fraction(c, d)
    c = pow(b, -1, d)
    if c == 0:
        c = d
    a = (b * c - 1) // d
    # Normalise a into [0, b).
    while a < 0:
        a += b
        c += d
    while a >= b:
        a -= b
        c -= d
    return Fraction(a, b), Fraction(c, d)


@dataclass(frozen=True)
class _Placement:
    """One of the two mirror-image homes of a signature in the labyrinth."""

    left: Fraction  # bracket's left Farey neighbour
    right: Fraction  # bracket's right Farey neighbour
    med: Fraction  # their mediant, always an endpoint of the MOS range
    lower: bool  # MOS occupies (left, med) when True, else (med, right)

    @property
    def range(self) -> Tuple[Fraction, Fraction]:
        return (self.left, self.med) if self.lower else (self.med, self.right)

    @property
    def small_vanishes(self) -> Fraction:
        """Endpoint where the small steps shrink to zero."""
        return self.left if self.lower else self.right

    @property
    def large_vanishes(self) -> Fraction:
        """Endpoint where the *inverse* scale's small steps shrink to zero."""
        return self.right if self.lower else self.left

    @property
    def is_bright(self) -> bool:
        """True when this range lies above ``1/2`` (the conventional generator)."""
        lo, hi = self.range
        return (lo + hi) > 1


def _placements(n_large: int, n_small: int) -> Tuple[_Placement, _Placement]:
    """The dark and bright placements of ``n_large L, n_small s``, in that order.

    A generator ``g`` and its complement ``1 - g`` build the same scale
    (Milne et al. §4), so every signature occupies two mirror-image ranges.
    Which of the two sub-ranges of a bracket the scale takes -- and therefore
    which endpoint is the vanishing one -- differs between them, so the two
    are constructed from opposite bracket solutions.
    """
    if n_large < 1 or n_small < 1:
        raise ValueError(f"both step counts must be >= 1, got {n_large}L {n_small}s")
    # Lower sub-range of the bracket: b = n_large large steps, d = n_small small.
    left_a, right_a = _solve_bracket(n_large, n_small)
    a = _Placement(left_a, right_a, mediant(left_a, right_a), lower=True)
    # Upper sub-range of the mirror bracket: d = n_large large, b = n_small small.
    left_b, right_b = _solve_bracket(n_small, n_large)
    b = _Placement(left_b, right_b, mediant(left_b, right_b), lower=False)
    return (a, b) if b.is_bright else (b, a)


def _placement(n_large: int, n_small: int, bright: bool) -> _Placement:
    dark_p, bright_p = _placements(n_large, n_small)
    return bright_p if bright else dark_p


def signature_brackets(
    n_large: int, n_small: int
) -> Tuple[Tuple[Fraction, Fraction], Tuple[Fraction, Fraction]]:
    """The two Farey brackets that host the MOS ``n_large L, n_small s``.

    A generator ``g`` and its complement ``1 - g`` produce the *same* scale
    (Milne et al. §4: "precisely the same scale is produced by generators of
    697 cents and 1200 - 697 = 503 cents"), so every signature occupies two
    mirror-image ranges in the labyrinth.

    Returns
    -------
    (dark_bracket, bright_bracket)
        Each a ``(left, right)`` Farey pair.  The *bright* bracket is the one
        whose MOS sub-range lies above ``1/2``; it is the one containing the
        conventional generator (e.g. the fifth rather than the fourth).

    Examples
    --------
    >>> signature_brackets(5, 2)
    ((Fraction(2, 5), Fraction(1, 2)), (Fraction(1, 2), Fraction(3, 5)))
    >>> signature_brackets(2, 5)
    ((Fraction(2, 5), Fraction(1, 2)), (Fraction(1, 2), Fraction(3, 5)))
    """
    dark_p, bright_p = _placements(n_large, n_small)
    return (dark_p.left, dark_p.right), (bright_p.left, bright_p.right)


def signature_ranges(
    n_large: int, n_small: int
) -> Tuple[Tuple[Fraction, Fraction], Tuple[Fraction, Fraction]]:
    """Valid generator ranges of ``n_large L, n_small s``, as ``(dark, bright)``.

    Within each open interval the scale keeps its identity while its two step
    sizes co-vary; at the endpoints it degenerates into an equal temperament.
    The two ranges are reflections of each other about ``1/2``.

    Examples
    --------
    The diatonic scale, per Milne et al. §3:

    >>> signature_ranges(5, 2)
    ((Fraction(2, 5), Fraction(3, 7)), (Fraction(4, 7), Fraction(3, 5)))

    Its inverse, the anti-diatonic:

    >>> signature_ranges(2, 5)
    ((Fraction(3, 7), Fraction(1, 2)), (Fraction(1, 2), Fraction(4, 7)))
    """
    dark_p, bright_p = _placements(n_large, n_small)
    return dark_p.range, bright_p.range


@dataclass(frozen=True)
class Landmarks:
    """The three equal temperaments that bound an MOS pair.

    Milne et al. §2 ("Landmark equal tunings"): as the generator moves, the
    two step sizes co-vary through three distinguished tunings.

    Attributes
    ----------
    equalized : Fraction
        Where large and small steps become the same size and the MOS meets its
        inverse.  Cardinality ``n_large + n_small``.
    small_vanishes : Fraction
        Where the ``n_small`` small steps shrink to zero, leaving ``n_large``
        equal steps.  This is the far end of the scale's valid range.
    large_vanishes : Fraction
        Where the *inverse* scale's small steps (``n_large`` of them) shrink to
        zero, leaving ``n_small`` equal steps.  Lies beyond ``equalized``, in
        the inverse scale's territory.
    bright : bool
        Which of the two mirror ranges these landmarks describe.
    """

    equalized: Fraction
    small_vanishes: Fraction
    large_vanishes: Fraction
    bright: bool

    @property
    def equalized_edo(self) -> int:
        return self.equalized.denominator

    @property
    def small_vanishes_edo(self) -> int:
        return self.small_vanishes.denominator

    @property
    def large_vanishes_edo(self) -> int:
        return self.large_vanishes.denominator

    def as_cents(self, period_cents: float = PERIOD_CENTS) -> dict:
        """The three landmarks in cents against a period of ``period_cents``."""
        return {
            "equalized": float(self.equalized) * period_cents,
            "small_vanishes": float(self.small_vanishes) * period_cents,
            "large_vanishes": float(self.large_vanishes) * period_cents,
        }


def mos_landmarks(n_large: int, n_small: int, bright: bool = True) -> Landmarks:
    """The three landmark tunings of ``n_large L, n_small s``.

    Examples
    --------
    The diatonic scale meets 7-EDO where its steps equalise, 5-EDO where its
    two small steps vanish, and 2-EDO where the anti-diatonic's five small
    steps vanish -- Milne et al. §2:

    >>> lm = mos_landmarks(5, 2)
    >>> lm.equalized, lm.small_vanishes, lm.large_vanishes
    (Fraction(4, 7), Fraction(3, 5), Fraction(1, 2))
    >>> lm.equalized_edo, lm.small_vanishes_edo, lm.large_vanishes_edo
    (7, 5, 2)

    The anti-diatonic meets 7-EDO too, vanishes into 2-EDO, and is bounded by
    the diatonic's own 5-EDO:

    >>> lm = mos_landmarks(2, 5)
    >>> lm.equalized, lm.small_vanishes, lm.large_vanishes
    (Fraction(4, 7), Fraction(1, 2), Fraction(3, 5))
    """
    p = _placement(n_large, n_small, bright)
    return Landmarks(
        equalized=p.med,
        small_vanishes=p.small_vanishes,
        large_vanishes=p.large_vanishes,
        bright=bright,
    )


def embedding(n_large: int, n_small: int, bright: bool = True) -> Tuple[int, Fraction]:
    """Lowest-cardinality MOS that embeds ``n_large L, n_small s``.

    Milne et al. §3: the embedding scale has ``2p + q`` tones and sits at the
    mediant of the embedded scale's two boundary tunings.

    Returns
    -------
    (cardinality, tuning)
        ``cardinality == 2 * n_large + n_small``; ``tuning`` is the generator
        fraction at which that embedding scale is equally tuned.

    Examples
    --------
    >>> embedding(5, 2)          # the diatonic lives inside 12
    (12, Fraction(7, 12))
    >>> embedding(2, 5)          # the anti-diatonic lives inside 9
    (9, Fraction(5, 9))
    """
    lm = mos_landmarks(n_large, n_small, bright=bright)
    tuning = mediant(lm.equalized, lm.small_vanishes)
    cardinality = 2 * n_large + n_small
    if tuning.denominator != cardinality:  # pragma: no cover - invariant guard
        raise AssertionError(
            f"embedding cardinality mismatch: mediant {tuning} has denominator "
            f"{tuning.denominator}, expected 2*{n_large}+{n_small}={cardinality}"
        )
    return cardinality, tuning


def coherence_range(
    n_large: int, n_small: int, bright: bool = True
) -> Tuple[Fraction, Fraction]:
    """Generator range over which the scale is coherent (proper).

    A scale is coherent when generic interval size and specific interval size
    agree monotonically -- every fifth larger than every fourth, and so on.
    Well-formed scales are coherent exactly while Blackwood's
    :math:`R = L / s < 2`, which is the range between the equalized landmark
    and the tuning at which the lowest-cardinality embedding scale is equally
    tuned (Milne et al. §2--3).

    Examples
    --------
    >>> coherence_range(5, 2)
    (Fraction(4, 7), Fraction(7, 12))
    >>> coherence_range(2, 5)
    (Fraction(5, 9), Fraction(4, 7))
    """
    lm = mos_landmarks(n_large, n_small, bright=bright)
    _, emb = embedding(n_large, n_small, bright=bright)
    lo, hi = sorted((lm.equalized, emb))
    return lo, hi


# --------------------------------------------------------------------------- #
# Step patterns (Christoffel words)
# --------------------------------------------------------------------------- #
def christoffel_word(n_large: int, n_small: int, lower: bool = True) -> str:
    """The Christoffel word on ``n_large`` L's and ``n_small`` s's.

    Milne et al. §2 footnote 5: the two step sizes of a well-formed scale are
    "distributed with maximal evenness … [their] distribution forms a
    Christoffel word".  The lower and upper words are reverses of each other.

    Examples
    --------
    >>> christoffel_word(5, 2)
    'sLLsLLL'
    >>> christoffel_word(2, 3)
    'ssLsL'
    """
    n = n_large + n_small
    if n == 0:
        return ""
    letters = []
    for i in range(1, n + 1):
        rise = (i * n_large) // n - ((i - 1) * n_large) // n
        letters.append("L" if rise else "s")
    word = "".join(letters)
    return word if lower else word[::-1]


def mos_word(n_large: int, n_small: int, mode: int = 0) -> str:
    """Step pattern of the ``mode``-th rotation of ``n_large L, n_small s``.

    ``mode=0`` is the Christoffel (lower mechanical) word; increasing ``mode``
    rotates left by one scale degree.  All ``n_large + n_small`` rotations are
    the modes of the scale.

    Examples
    --------
    >>> mos_word(5, 2, mode=0)
    'sLLsLLL'
    >>> mos_word(5, 2, mode=1)
    'LLsLLLs'
    """
    word = christoffel_word(n_large, n_small)
    if not word:
        return word
    k = mode % len(word)
    return word[k:] + word[:k]


def word_from_generator(g: float, cardinality: int) -> str:
    """Step pattern obtained by actually stacking ``g`` ``cardinality`` times.

    This is the empirical counterpart of :func:`mos_word`: it builds the scale,
    sorts it, and labels each step L or s.  Used to cross-check the
    combinatorics against the geometry.

    Examples
    --------
    >>> word_from_generator(math.log2(3 / 2), 7)
    'LLLsLLs'
    """
    steps = _raw_steps(g, cardinality)
    if not steps:
        return ""
    lo, hi = min(steps), max(steps)
    if math.isclose(lo, hi, rel_tol=1e-9, abs_tol=1e-12):
        return "L" * cardinality
    mid = (lo + hi) / 2.0
    return "".join("L" if s > mid else "s" for s in steps)


def _raw_steps(g: float, cardinality: int) -> List[float]:
    """Consecutive step sizes (as period fractions) of the stacked scale."""
    pitches = sorted((i * g) % 1.0 for i in range(cardinality))
    return [
        (pitches[(i + 1) % cardinality] - pitches[i]) % 1.0
        for i in range(cardinality)
    ]


def degrees_from_generator(g: float, cardinality: int) -> List[float]:
    """Scale degrees as period fractions in ``[0, 1)``, sorted ascending."""
    return sorted((i * g) % 1.0 for i in range(cardinality))


def step_sizes(g: float, cardinality: int) -> Tuple[float, float]:
    """``(large, small)`` step size as fractions of the period.

    For a degenerate (equal) tuning both values coincide.
    """
    steps = _raw_steps(g, cardinality)
    if not steps:
        return (0.0, 0.0)
    return (max(steps), min(steps))


# --------------------------------------------------------------------------- #
# Ratio <-> generator-fraction conversions
# --------------------------------------------------------------------------- #
def generator_fraction(generator: float, period: float = 2.0) -> float:
    """Convert a frequency ratio to its position ``g`` in the labyrinth.

    The result is reduced into ``(0, 1)`` by the period, exactly as a generator
    is octave-reduced when a scale is built.

    Examples
    --------
    >>> round(generator_fraction(3 / 2), 6)
    0.584963
    >>> round(generator_fraction(3 / 2, period=3), 5)   # a pseudo-octave
    0.36907
    """
    if generator <= 0:
        raise ValueError(f"generator ratio must be positive, got {generator!r}")
    if period <= 1:
        raise ValueError(f"period ratio must exceed 1, got {period!r}")
    return (math.log(generator) / math.log(period)) % 1.0


def fraction_to_generator(g: float, period: float = 2.0) -> float:
    """Convert a labyrinth position back to a frequency ratio.

    Inverse of :func:`generator_fraction` (up to period reduction).

    Examples
    --------
    >>> round(fraction_to_generator(math.log2(3 / 2)), 6)
    1.5
    """
    if period <= 1:
        raise ValueError(f"period ratio must exceed 1, got {period!r}")
    return period**g


def common_tones(
    generators: Sequence[float],
    period: float = 2.0,
    max_cardinality: int = 18,
    tol_cents: float = 5.0,
) -> List[float]:
    """Positions where two different generators land on the same tone.

    A shared tone belongs to no single scale, which is why it is easy to miss
    and worth locating: common tones are what let one tuning modulate into
    another, and on the labyrinth they are the angles at which two generators'
    rings line up.  Each generator contributes its largest MOS within
    ``max_cardinality``.

    Parameters
    ----------
    generators : sequence of float
        Generator fractions in ``(0, 1)``.  Fewer than two gives no pairs and
        an empty result.
    period : float, default 2.0
        Period as a frequency ratio; only affects what ``tol_cents`` means.
    max_cardinality : int, default 18
    tol_cents : float, default 5.0
        How close two tones must be to count as shared.

    Returns
    -------
    list of float
        Period fractions, ascending, midway between each coinciding pair.

    Notes
    -----
    A generator and its complement ``1 - g`` build the same scale, but
    *mirrored*, so as pitch-class sets rooted at zero they share only the root.
    Sameness of scale and sameness of tones are different questions, and this
    function answers the second one.

    Examples
    --------
    Two generators of the same equal division share all of it -- both 5\\12 and
    7\\12 run through every step of 12-EDO:

    >>> len(common_tones([7 / 12, 5 / 12], max_cardinality=12))
    12

    Pythagorean and meantone fifths drift apart by about 5.2 cents per step, so
    at a 5-cent tolerance only the root survives; widen it and the near ones
    reappear:

    >>> g = math.log2(3 / 2)
    >>> [round(t * 1200, 1) for t in common_tones([g, 18 / 31], max_cardinality=12)]
    [0.0]
    >>> len(common_tones([g, 18 / 31], max_cardinality=12, tol_cents=12))
    3

    Unrelated generators share only the root:

    >>> [round(t, 6) for t in common_tones([g, 0.7071], max_cardinality=7)]
    [0.0]

    Fewer than two generators gives nothing to compare:

    >>> common_tones([g])
    []
    """
    if tol_cents < 0:
        raise ValueError(f"tol_cents must be non-negative, got {tol_cents!r}")
    if period <= 1:
        raise ValueError(f"period ratio must exceed 1, got {period!r}")

    pools: List[List[float]] = []
    for g in generators:
        g = float(g) % 1.0
        if not 0.0 < g < 1.0:
            continue
        cards = [
            c
            for c in mos_cardinalities(g, max_cardinality, include_trivial=True)
            if c >= 3
        ]
        if cards:
            pools.append(degrees_from_generator(g, cards[-1]))
    if len(pools) < 2:
        return []

    period_cents = PERIOD_CENTS * math.log2(period)
    shared = set()
    for i in range(len(pools)):
        for j in range(i + 1, len(pools)):
            for a in pools[i]:
                for b in pools[j]:
                    gap = abs(a - b)
                    if min(gap, 1.0 - gap) * period_cents <= tol_cents:
                        shared.add(round((a + b) / 2.0, 9))
    return sorted(shared)


def fold_generator(g: float) -> float:
    """Fold ``g`` into ``(0, 0.5]`` using the labyrinth's mirror symmetry.

    A generator and its complement within the period build the same scale
    (Milne et al. §4), so ``g`` and ``1 - g`` are musically identical.  Folding
    gives a canonical representative -- useful for deduplicating candidate
    generators, though the *bright* form ``g > 1/2`` is usually the one quoted.

    Examples
    --------
    >>> round(fold_generator(math.log2(3 / 2)), 6)   # the fifth folds to the fourth
    0.415037
    """
    g = g % 1.0
    return min(g, 1.0 - g)
