"""Build (and execute, embedding outputs) the math_series docs notebook.

The docs build does not execute notebooks (``nb_execution_mode = "off"``), so
notebooks must ship with their outputs. nbconvert isn't available here, so we
execute the cells in-process and embed captured stdout + figures as outputs.
The stored cell *source* stays clean (no sys.path hacks); execution-time setup
(repo on path, chdir to the notebook dir) is done only in this builder.

Run from the repo root::

    python scripts/build_math_series_notebook.py
"""

import base64
import contextlib
import io
import json
import os
import sys

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
NB_DIR = os.path.join(REPO, "docs", "examples", "math_series")
NB_PATH = os.path.join(NB_DIR, "math_series.ipynb")

# --------------------------------------------------------------------------- cells
MD = "markdown"
CODE = "code"

CELLS = [
    (MD, """# Matching biosignals to mathematical series

`biotuner.math_series` asks a simple question: **which classic mathematical
sequence — Fibonacci, Lucas, harmonics, Farey, … — is most present in a
biosignal's peak-ratio structure?** It takes a fitted `compute_biotuner`
object (or a `HarmonicInput`), compares its peak ratios (or *extended*-peak
ratios) against the ratios generated by each series, and reports the match
proportions. The matched subset of the winning series can then be turned into
a scale or a consonance-selected mode.

This notebook walks through the full workflow on a real EEG recording.
"""),

    (MD, """## 1. Extract peaks and ratios from the EEG

We load an example recording (104 channels × 4000 samples @ 1000 Hz), pick one
channel, and extract its spectral **peaks** and the harmonically **extended**
peaks. Both yield octave-reduced peak ratios in `[1, 2)` — the input the
matcher works on."""),

    (CODE, """import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

from biotuner.biotuner_object import compute_biotuner

data = np.load("../data/EEG_example.npy")   # (104 channels, 4000 samples)
sf = 1000

bt = compute_biotuner(sf=sf, peaks_function="FOOOF", precision=0.5)
bt.peaks_extraction(data[0], min_freq=2, max_freq=40, n_peaks=6)
bt.peaks_extension(n_harm=5)

print("peaks (Hz):          ", np.round(bt.peaks, 2))
print("peak ratios:         ", [round(r, 3) for r in bt.peaks_ratios])
print("n extended ratios:   ", len(bt.extended_peaks_ratios))"""),

    (MD, """## 2. Which mathematical series is present?

Feed the fitted object to `math_series`. `analyze()` scores every series; the
`summary()` table ranks them by the proportion of the EEG's peak ratios each
one reproduces."""),

    (CODE, """from biotuner.math_series import math_series

ms = math_series(bt, ratios_source="peaks_ratios", maxdenom=24).analyze()
print("Best-matching series:", ms.best_series, "\\n")
print(ms.summary())"""),

    (CODE, """ms.plot_proportions();"""),

    (MD, """### Peaks vs. extended peaks

`ratios_source` switches between the raw spectral peak ratios and the
harmonically extended ones — they can favour different series."""),

    (CODE, """ms_ext = math_series(bt, ratios_source="extended_peaks_ratios", maxdenom=24).analyze()
print("peaks    -> best:", ms.best_series)
print("extended -> best:", ms_ext.best_series)
ms_ext.plot_proportions();"""),

    (MD, """### Where do the peaks sit? — the ratio-pairs scatter

Each small dot is a pair of series elements; the large dots are the pairs whose
ratio matches one of the EEG's peak ratios."""),

    (CODE, """ms.plot_ratio_pairs();"""),

    (MD, """## 3. Across the whole montage

Running the matcher on every channel answers the population question: which
series dominates this recording's peak-ratio structure?"""),

    (CODE, """best_counts = {s: 0 for s in ms.series_names}
for ch in range(data.shape[0]):
    try:
        bt_ch = compute_biotuner(sf=sf, peaks_function="FOOOF", precision=0.5)
        bt_ch.peaks_extraction(data[ch], min_freq=2, max_freq=40, n_peaks=6)
        m = math_series(bt_ch, ratios_source="peaks_ratios", maxdenom=24).analyze()
        best_counts[m.best_series] += 1
    except Exception:
        continue

print("Best series per channel:", best_counts)

from biotuner.plot_config import set_biotuner_style, get_color_palette
set_biotuner_style()
plt.figure(figsize=(6, 3.2))
plt.bar(list(best_counts), list(best_counts.values()),
        color=get_color_palette("biotuner_gradient", len(best_counts)))
plt.ylabel("channels where it wins")
plt.title("Most-present series across the montage");"""),

    (MD, """## 4. Derive musical structures

The matched subset of the winning series is a scale; `series_mode` reduces it
to a consonance-selected mode."""),

    (CODE, """print("Scale from best series:", [round(x, 3) for x in ms.series_scale()])
print("7-note mode (pairwise):", [round(x, 3) for x in ms.series_mode(n_steps=7, method="pairwise")])
print("Scale in cents:        ", [round(c, 1) for c in ms.scale_cents()])"""),

    (MD, """## 5. Creative views — where the (extended) peaks sit among the series

These are built-in `math_series` methods. We build a matcher on the
*extended*-peak ratios and call each visualization. ``order=`` thins the
lattice for legibility without changing the matching settings."""),

    (CODE, """ms_ext = math_series(bt, ratios_source="extended_peaks_ratios", maxdenom=24).analyze()
print("best (extended):", ms_ext.best_series)
ms_ext.plot_octave_wheel(order=13);"""),

    (MD, """### Cents ruler — the ratio lattice

Each series as a lane of ratio-ticks on a 0–1200 cents axis (bold = matched);
guide lines drop from each signal peak."""),

    (CODE, """ms_ext.plot_cents_ruler(order=13);"""),

    (MD, """### How tightly each series fits

For every extended peak, the cents distance to the *nearest* ratio of each
series (lower = closer). A density-aware view — note Farey is dense yet does
not fit tightest, so this is not just a density effect."""),

    (CODE, """ms_ext.plot_fit_landscape();"""),

    (MD, """### Simplicity bubbles

Each series ratio as a bubble sized by simplicity (bigger = simpler fraction).
Do the signal peaks land on the simple rungs? Outlined bubbles are matched."""),

    (CODE, """ms_ext.plot_simplicity_bubbles(order=13);"""),

    (MD, """### Across-octave frequency comb (the series as canvas)

Flip it around: each series, tiled across octaves and scaled to best fit the
signal, becomes a frequency grid; the signal peaks (Hz) snap onto the nearest
step, with each lane's mean miss in cents."""),

    (CODE, """ms_ext.plot_series_comb(order=7);"""),

    (MD, """## 6. Effect of `order` on matching

`order` sets how many terms each series generates — more terms means a denser
ratio set, which trivially matches more peaks. So the absolute proportions rise
with `order` and then saturate. The practical lesson: **keep `order` fixed when
comparing series** — only proportions computed at the same `order` (and
`maxdenom`) are comparable. The *ranking* is usually far more stable than the
absolute values."""),

    (CODE, """from biotuner.plot_config import get_color_palette

orders = list(range(5, 41, 3))
series = ms.series_names
colors = dict(zip(series, get_color_palette("biotuner_gradient", len(series))))
fig, ax = plt.subplots(figsize=(8.5, 4.5))
for name in series:
    props = [math_series(bt, ratios_source="peaks_ratios", order=o, maxdenom=24)
             .analyze().series_scores[name]["proportion"] for o in orders]
    ax.plot(orders, props, "-o", color=colors[name], label=name)
ax.set_xlabel("order (terms generated per series)")
ax.set_ylabel("match proportion — peak ratios")
ax.set_title("Effect of `order` on matching (keep it fixed when comparing series)")
ax.legend();"""),

    (MD, """## 7. Parameters to control

| Parameter | Default | Controls |
|---|---|---|
| `ratios_source` | `"peaks_ratios"` | Which EEG ratios to analyse: raw peaks vs `"extended_peaks_ratios"`. |
| `maxdenom` | `24` | **Matching strictness.** Ratios match if their `limit_denominator(maxdenom)` fractions agree. Lower (≈12–16) = lenient, higher (≈40–60) = strict. Useful range ≈16–48. |
| `series_names` | `["fibonacci", "lucas", "farey", "harmonics"]` | Which series to compare (also available: `padovan, pell, jacobsthal, mersenne, hofstadter_q, subharmonics, triangular`). |
| `order` | `20` | Terms generated per series (Farey order for `farey`); higher = denser. Keep fixed when comparing signals. |
| `octave` | `2.0` | Period the ratios fold into. |

`series_mode()` adds `n_steps`, `method` (`"subset"` exhaustive vs `"pairwise"` greedy) and `function` (consonance metric).

**Rule of thumb:** the two dials you'll actually turn are `ratios_source`
(peaks vs extended) and `maxdenom` (how forgiving the match is). Keep `order`
and `maxdenom` fixed across signals when comparing series — proportions are
only comparable under the same settings.

All of these visualizations are methods on `math_series` — `plot_proportions`,
`plot_ratio_pairs`, `plot_octave_wheel`, `plot_cents_ruler`,
`plot_fit_landscape`, `plot_simplicity_bubbles`, and `plot_series_comb` — so you
can call them on any biotuner object. See the `biotuner.math_series` API page
for the full reference.
"""),
]


# --------------------------------------------------------------------------- exec
def src_lines(text):
    return text.splitlines(keepends=True) or [""]


def run():
    os.makedirs(NB_DIR, exist_ok=True)
    sys.path.insert(0, REPO)            # use the local biotuner package
    os.chdir(NB_DIR)                    # so "../data/EEG_example.npy" resolves

    ns = {}
    nb_cells = []
    count = 0
    for kind, text in CELLS:
        if kind == MD:
            nb_cells.append({"cell_type": "markdown", "metadata": {}, "source": src_lines(text)})
            continue
        count += 1
        plt.close("all")
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            exec(compile(text, "<cell>", "exec"), ns)
        outputs = []
        out_text = buf.getvalue()
        if out_text:
            outputs.append({"output_type": "stream", "name": "stdout",
                            "text": src_lines(out_text)})
        for num in plt.get_fignums():
            fig = plt.figure(num)
            b = io.BytesIO()
            fig.savefig(b, format="png", dpi=110, bbox_inches="tight")
            b64 = base64.b64encode(b.getvalue()).decode("ascii")
            outputs.append({"output_type": "display_data", "metadata": {},
                            "data": {"image/png": b64, "text/plain": ["<Figure>"]}})
        plt.close("all")
        nb_cells.append({"cell_type": "code", "execution_count": count,
                         "metadata": {}, "outputs": outputs, "source": src_lines(text)})
        print(f"  executed code cell {count}: {len(outputs)} output(s)")

    notebook = {
        "cells": nb_cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "pygments_lexer": "ipython3"},
        },
        "nbformat": 4,
        "nbformat_minor": 4,
    }
    with open(NB_PATH, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=1, ensure_ascii=False)
    print(f"Wrote {NB_PATH}")


if __name__ == "__main__":
    run()
