"""Surge XT bundle exporter — wavetable + .scl + .kbm + README.

Module type: Functions

Surge XT is a free, open-source synthesizer with first-class microtuning
support — likely the largest user community for biosignal-derived
microtonal instruments. This exporter produces a folder containing:

    <bundle>.wav     — Surge wavetable (2048 × n_frames)
    <bundle>.scl     — Scala scale (matched tuning)
    <bundle>.kbm     — Keyboard mapping
    README.md        — loading instructions for Surge users

Optional .fxp generation (Surge's binary patch format) is intentionally
not implemented in Phase 2 — the wavetable + tuning files are all a
Surge user needs to load the instrument in two clicks.
"""

from __future__ import annotations

import os
from textwrap import dedent

from biotuner.harmonic_timbre.cross_modal import write_sidecar
from biotuner.harmonic_timbre.exporters._common import bundle_paths, write_manifest
from biotuner.harmonic_timbre.exporters.to_wavetable import export_wavetable
from biotuner.harmonic_timbre.exporters.tuning_files import export_tuning_files
from biotuner.harmonic_timbre.timbre import Timbre


_README_TEMPLATE = dedent("""
# {bundle_name} — Surge XT bundle

Generated by **biotuner.harmonic_timbre**.

## Files

- `{bundle_name}.wav` — wavetable ({n_frames} frame(s) × 2048 samples)
- `{bundle_name}.scl` — Scala scale (matched tuning, {n_steps} steps)
- `{bundle_name}.kbm` — Keyboard mapping
- `{bundle_name}_sidecar/` — provenance metadata + harmonic-geometry
  signature image

## Loading in Surge XT

1. Open Surge XT.
2. Drag `{bundle_name}.wav` onto the Wavetable oscillator (osc 1/2/3).
3. Right-click the synth header → **Tuning** → **Load .scl Scale...**
   and pick `{bundle_name}.scl`.
4. Right-click the synth header → **Tuning** → **Load .kbm Keyboard
   Mapping...** and pick `{bundle_name}.kbm`.
5. Play. Surge will respect both the wavetable timbre and the matched
   tuning across the keyboard.

## Provenance

- Matching method: `{matching_method}`
- Number of partials: {n_partials}
- Source: see `{bundle_name}_sidecar/{bundle_name}_metadata.json` for
  the full provenance trail (which biotuner fields fed the timbre,
  matched_tuning, scale_source, …).

The harmonograph image in the sidecar is the visual fingerprint of
this instrument's harmonic structure — it shares the same ratios as
the audio it accompanies.
""").strip()


def export_surge_bundle(
    timbre: Timbre,
    out_dir: str,
    *,
    bundle_name: str = "biotuner_timbre",
    n_wavetable_frames: int = 8,
    a4: float = 440.0,
    middle_note: int = 60,
    reference_note: int = 69,
) -> dict:
    """Write a Surge XT bundle: wavetable + ``.scl`` + ``.kbm`` + README + sidecar.

    Parameters
    ----------
    timbre : Timbre
    out_dir : str
        Output directory (created if missing).
    bundle_name : str, default='biotuner_timbre'
        Stem used for all output files.
    n_wavetable_frames : int, default=8
        Number of wavetable frames (Surge XT supports a brightness sweep
        across the table). Set to 1 for a single-cycle wavetable.
    a4 : float, default=440.0
        Reference frequency for ``.kbm`` keyboard anchoring.
    middle_note : int, default=60
        MIDI note that maps to scale degree 0 (the unison).
    reference_note : int, default=69

    Returns
    -------
    dict
        ``{'wavetable', 'scl', 'kbm', 'readme', 'sidecar', 'manifest'}``.
    """
    if timbre.matched_tuning is None:
        raise ValueError(
            "export_surge_bundle: timbre.matched_tuning is None — Surge bundle requires a tuning."
        )

    paths = bundle_paths(out_dir, bundle_name)
    os.makedirs(paths["dir"], exist_ok=True)

    # Wavetable (Surge target conventions)
    wt_path = os.path.join(paths["dir"], f"{bundle_name}.wav")
    wt_result = export_wavetable(
        timbre, wt_path,
        n_frames=n_wavetable_frames,
        synth_target="surge",
        include_sidecar=False,  # we write the sidecar once at the bundle level
    )

    # Scale + keyboard map
    tuning = export_tuning_files(
        timbre, paths["dir"],
        bundle_name=bundle_name,
        middle_note=middle_note,
        reference_note=reference_note,
        reference_freq=a4,
    )

    # README
    ratios = list(timbre.matched_tuning)
    n_steps = len(ratios) - 1 if abs(ratios[0] - 1.0) < 1e-9 else len(ratios)
    readme_path = os.path.join(paths["dir"], "README.md")
    readme_text = _README_TEMPLATE.format(
        bundle_name=bundle_name,
        n_frames=n_wavetable_frames,
        n_steps=n_steps,
        matching_method=timbre.matching_method or "(unspecified)",
        n_partials=timbre.n_partials(),
    )
    with open(readme_path, "w", encoding="utf-8") as fp:
        fp.write(readme_text)

    # Sidecar bundle (single, at the bundle level)
    sidecar = write_sidecar(timbre, paths["sidecar"], stem=bundle_name)

    # Manifest
    manifest = {
        "format": "biotuner_surge_bundle",
        "format_version": 1,
        "bundle_name": bundle_name,
        "files": {
            "wavetable": os.path.relpath(wt_path, paths["dir"]).replace(os.sep, "/"),
            "scl": os.path.relpath(tuning["scl"], paths["dir"]).replace(os.sep, "/"),
            "kbm": os.path.relpath(tuning["kbm"], paths["dir"]).replace(os.sep, "/"),
            "readme": os.path.relpath(readme_path, paths["dir"]).replace(os.sep, "/"),
        },
        "n_wavetable_frames": int(n_wavetable_frames),
        "timbre": {
            "matched_tuning": ratios,
            "matching_method": timbre.matching_method,
            "n_partials": timbre.n_partials(),
        },
    }
    manifest_path = write_manifest(paths["manifest"], manifest)

    return {
        "wavetable": wt_path,
        "scl": tuning["scl"],
        "kbm": tuning["kbm"],
        "readme": readme_path,
        "sidecar": sidecar,
        "manifest": manifest_path,
    }
