"""SFZ exporter — multi-pitch sample bundle + .sfz instrument document.

Module type: Functions

SFZ is a plain-text sampler instrument format supported by Sforzando
(free), sfizz (free, open source), and Decent Sampler (free). The
output of this exporter is a folder containing:

    <bundle>.sfz             — the instrument document
    <bundle>_samples/*.wav   — per-pitch samples
    <bundle>.scl + .kbm      — companion tuning files
    <bundle>_sidecar/        — signature.png + metadata.json

A musician drags the ``.sfz`` into Sforzando / sfizz / Decent Sampler
and gets the matched tuning + matched timbre playable on a MIDI
keyboard.

Spec reference
--------------
SFZ 2.0: https://sfzformat.com/legacy/
"""

from __future__ import annotations

import os
from typing import Iterable

# soundfile is a heavy/optional dependency (libsndfile binding). Import lazily
# so ``import biotuner`` succeeds in environments without libsndfile.
try:
    import soundfile as sf
except ImportError:  # pragma: no cover - environment-dependent
    sf = None

from biotuner.harmonic_timbre.cross_modal import write_sidecar
from biotuner.harmonic_timbre.exporters._common import (
    bundle_paths,
    midi_note_name,
    midi_to_hz,
    safe_filename,
    write_manifest,
)
from biotuner.harmonic_timbre.exporters.tuning_files import export_tuning_files
from biotuner.harmonic_timbre.timbre import Timbre


_DEFAULT_PITCHES = (36, 48, 60, 72, 84)  # C2..C6


def export_sfz(
    timbre: Timbre,
    out_dir: str,
    *,
    bundle_name: str = "biotuner_timbre",
    reference_pitches_midi: Iterable[int] = _DEFAULT_PITCHES,
    duration: float = 4.0,
    samplerate: int = 48000,
    bit_depth: int = 24,
    a4: float = 440.0,
    write_tuning_files: bool = True,
    include_sidecar: bool = True,
) -> dict:
    """Export an SFZ instrument + samples + companion files.

    Parameters mirror :func:`export_wav_pack`. Returns a dict of paths.

    The SFZ document maps each rendered sample to a contiguous keyboard
    region. ``pitch_keycenter`` is set per-region to the rendered MIDI
    note so the host transposes correctly. If ``write_tuning_files``
    is True, a ``.scl`` + ``.kbm`` pair is written next to the SFZ; the
    musician loads them in their host's microtuning slot to play the
    matched scale (SFZ itself has no microtuning syntax that's
    universally honored).
    """
    timbre.validate()

    pitches = sorted(reference_pitches_midi)
    if not pitches:
        raise ValueError("export_sfz: reference_pitches_midi is empty")

    paths = bundle_paths(out_dir, bundle_name)
    os.makedirs(paths["samples"], exist_ok=True)
    os.makedirs(paths["dir"], exist_ok=True)

    if sf is None:
        raise ImportError(
            "export_sfz requires the 'soundfile' package. "
            "Install with: pip install soundfile"
        )
    subtype = {16: "PCM_16", 24: "PCM_24", 32: "FLOAT"}.get(bit_depth)
    if subtype is None:
        raise ValueError(f"export_sfz: unsupported bit_depth {bit_depth}")

    # Render samples
    wav_paths: list[tuple[int, str]] = []
    for midi_note in pitches:
        f0 = midi_to_hz(midi_note, a4=a4)
        audio = timbre.synthesize(
            samplerate=samplerate, duration=duration, base_freq=f0,
        )
        name = safe_filename(f"{midi_note:03d}_{midi_note_name(midi_note)}.wav")
        wav_path = os.path.join(paths["samples"], name)
        sf.write(wav_path, audio, samplerate, subtype=subtype)
        wav_paths.append((midi_note, wav_path))

    # Compute per-region [lokey, hikey] split points (midpoint-rule)
    sfz_path = os.path.join(paths["dir"], f"{bundle_name}.sfz")
    rel_samples_dir = os.path.relpath(paths["samples"], paths["dir"]).replace(os.sep, "/")

    sfz_lines = [
        "// SFZ instrument generated by biotuner.harmonic_timbre",
        f"// matched_tuning = {timbre.matched_tuning}",
        f"// matching_method = {timbre.matching_method}",
        f"// metadata = {dict(timbre.metadata)}",
        "",
        "<control>",
        f"default_path={rel_samples_dir}/",
        "",
        "<global>",
        "ampeg_release=0.4",
        "loop_mode=no_loop",
        "",
    ]

    notes = [n for n, _ in wav_paths]
    for i, (midi_note, wav_path) in enumerate(wav_paths):
        if i == 0:
            lokey = 0
        else:
            lokey = (notes[i - 1] + midi_note) // 2 + 1
        if i == len(wav_paths) - 1:
            hikey = 127
        else:
            hikey = (midi_note + notes[i + 1]) // 2
        sample_name = os.path.basename(wav_path)
        sfz_lines += [
            "<region>",
            f"sample={sample_name}",
            f"lokey={lokey}",
            f"hikey={hikey}",
            f"pitch_keycenter={midi_note}",
            "",
        ]

    with open(sfz_path, "w", encoding="utf-8") as fp:
        fp.write("\n".join(sfz_lines))

    result: dict = {
        "sfz": sfz_path,
        "samples_dir": paths["samples"],
        "wavs": [p for _, p in wav_paths],
    }

    # Companion tuning files
    if write_tuning_files and timbre.matched_tuning is not None:
        try:
            tuning = export_tuning_files(
                timbre, paths["dir"], bundle_name=bundle_name,
                reference_freq=a4,
            )
            result.update(tuning)
        except ValueError:
            # no matched_tuning set — skip silently
            pass

    # Sidecar bundle
    if include_sidecar:
        sidecar = write_sidecar(timbre, paths["sidecar"], stem=bundle_name)
        result["sidecar"] = sidecar

    # Write a manifest summarizing the bundle
    manifest = {
        "format": "biotuner_sfz_bundle",
        "format_version": 1,
        "bundle_name": bundle_name,
        "samplerate": samplerate,
        "bit_depth": bit_depth,
        "duration_seconds": duration,
        "a4_hz": a4,
        "files": {
            "sfz": os.path.relpath(sfz_path, paths["dir"]).replace(os.sep, "/"),
            "samples": [
                os.path.relpath(p, paths["dir"]).replace(os.sep, "/")
                for _, p in wav_paths
            ],
        },
        "timbre": {
            "matched_tuning": list(timbre.matched_tuning) if timbre.matched_tuning is not None else None,
            "matching_method": timbre.matching_method,
            "n_partials": timbre.n_partials(),
        },
    }
    manifest_path = write_manifest(paths["manifest"], manifest)
    result["manifest"] = manifest_path

    return result
