"""Tuning file exporters: ``.scl`` (Scala) and ``.kbm`` (keyboard map).

Module type: Functions

Wraps :func:`biotuner.biotuner_utils.create_SCL` for Scala output and
adds a small ``.kbm`` writer (the standard keyboard-mapping companion
file). Together a ``.scl`` + ``.kbm`` pair is loadable by virtually
every microtonal-capable host: Sforzando, sfizz, Surge XT, ZynAddSubFX,
Yoshimi, Pianoteq, Scala, etc.

Spec references
---------------
.scl: http://www.huygens-fokker.org/scala/scl_format.html
.kbm: http://www.huygens-fokker.org/scala/help.htm#mappings
"""

from __future__ import annotations

import math
import os

from biotuner.harmonic_timbre.timbre import Timbre


# ---------------------------------------------------------------------------
# .scl writer (uses biotuner_utils.create_SCL when available, with our own
# fallback path so that tests don't depend on its plot/IO side effects).
# ---------------------------------------------------------------------------

def _ratio_to_cents(r: float) -> float:
    return 1200.0 * math.log2(r)


def _format_scl_line(ratio: float) -> str:
    """Format one scale degree line for an SCL file.

    Per the spec a line is either an integer ratio "n/d" or a cents
    value "x.xxxxx". We emit cents with 5 decimals (Scala default).
    """
    return f"{_ratio_to_cents(ratio):.5f}"


def export_scl(
    timbre_or_ratios,
    out_path: str,
    *,
    name: str | None = None,
    description: str | None = None,
) -> str:
    """Write a Scala ``.scl`` file from a Timbre or a raw list of ratios.

    Parameters
    ----------
    timbre_or_ratios : Timbre | iterable of float
        If a Timbre, uses ``timbre.matched_tuning``. Otherwise an
        iterable of ratios (must include the equave at the end).
    out_path : str
        Output path. ``.scl`` is appended if not already present.
    name : str, optional
        Scale name embedded in the file. Defaults to the file stem.
    description : str, optional
        First-line description. Defaults to a short auto-generated note.

    Returns
    -------
    str
        Path to the written file.
    """
    if isinstance(timbre_or_ratios, Timbre):
        if timbre_or_ratios.matched_tuning is None:
            raise ValueError(
                "export_scl: timbre has no matched_tuning; cannot derive a scale"
            )
        ratios = list(timbre_or_ratios.matched_tuning)
    else:
        ratios = [float(r) for r in timbre_or_ratios]
    if not ratios:
        raise ValueError("export_scl: empty ratios")

    if not out_path.endswith(".scl"):
        out_path = out_path + ".scl"
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)

    if name is None:
        name = os.path.splitext(os.path.basename(out_path))[0]
    if description is None:
        description = (
            f"Scale generated by biotuner.harmonic_timbre — {len(ratios) - 1} steps"
        )

    # Per the spec the first ratio (1/1, the unison) is implicit and not
    # listed; the file lists steps 1..n where step n is the equave.
    if abs(ratios[0] - 1.0) < 1e-9:
        scale_steps = ratios[1:]
    else:
        scale_steps = ratios

    lines: list[str] = []
    lines.append(f"! {os.path.basename(out_path)}")
    lines.append(f"!")
    lines.append(description)
    lines.append(f" {len(scale_steps)}")
    lines.append("!")
    for r in scale_steps:
        lines.append(f" {_format_scl_line(r)}")
    body = "\n".join(lines) + "\n"

    with open(out_path, "w", encoding="utf-8") as fp:
        fp.write(body)
    return out_path


# ---------------------------------------------------------------------------
# .kbm writer
# ---------------------------------------------------------------------------

def export_kbm(
    out_path: str,
    *,
    n_scale_steps: int,
    middle_note: int = 60,
    reference_note: int = 69,
    reference_freq: float = 440.0,
    formal_octave: int = 0,
    keyboard_size: int = 128,
    first_midi_note: int = 0,
    last_midi_note: int = 127,
) -> str:
    """Write a Scala ``.kbm`` keyboard mapping file.

    Phase 1 default: a *linear* mapping where MIDI note ``middle_note``
    is the unison (1/1) of the scale, and the scale is repeated above
    and below per its equave. ``reference_note`` and ``reference_freq``
    pin the absolute pitch.

    Notes
    -----
    The KBM format is heavily comment-driven; we follow the canonical
    blank-line-then-value layout used by Sforzando, sfizz, and Surge.
    """
    if not out_path.endswith(".kbm"):
        out_path = out_path + ".kbm"
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)

    map_size = n_scale_steps  # one mapping entry per scale step

    lines = [
        f"! Template for a keyboard mapping",
        f"!",
        f"! Size of map. The pattern repeats every so many keys:",
        f" {map_size}",
        f"! First MIDI note number to retune:",
        f" {first_midi_note}",
        f"! Last MIDI note number to retune:",
        f" {last_midi_note}",
        f"! Middle note where the first entry of the mapping is mapped to:",
        f" {middle_note}",
        f"! Reference note for which frequency is given:",
        f" {reference_note}",
        f"! Frequency to tune the above note to (in Hz):",
        f" {reference_freq:.6f}",
        f"! Scale degree to consider as formal octave (determines difference in pitch",
        f"! between adjacent mapping patterns):",
        f" {formal_octave if formal_octave > 0 else n_scale_steps}",
        f"! Mapping.",
        f"! The numbers represent scale degrees mapped to keys. The first",
        f"! entry is for the given middle note, the next for the next higher",
        f"! key, and so on. An empty line or the value -1 means an unmapped key.",
    ]
    for i in range(map_size):
        lines.append(f" {i}")

    body = "\n".join(lines) + "\n"
    with open(out_path, "w", encoding="utf-8") as fp:
        fp.write(body)
    return out_path


# ---------------------------------------------------------------------------
# Convenience: write both
# ---------------------------------------------------------------------------

def export_tuning_files(
    timbre: Timbre,
    out_dir: str,
    *,
    bundle_name: str = "biotuner_scale",
    middle_note: int = 60,
    reference_note: int = 69,
    reference_freq: float = 440.0,
    description: str | None = None,
) -> dict[str, str]:
    """Write a ``.scl`` + ``.kbm`` pair anchored on the same scale.

    Returns a dict with ``'scl'`` and ``'kbm'`` keys mapping to the
    written file paths. The two files are designed to be loaded as a
    pair by every microtonal-capable host.
    """
    if timbre.matched_tuning is None:
        raise ValueError(
            "export_tuning_files: timbre.matched_tuning is None — cannot derive .scl"
        )

    os.makedirs(out_dir, exist_ok=True)
    scl_path = os.path.join(out_dir, bundle_name)
    kbm_path = os.path.join(out_dir, bundle_name)

    scl = export_scl(
        timbre, scl_path,
        name=bundle_name, description=description,
    )

    # Number of scale steps = len(matched_tuning) - 1 because the equave
    # is included as the last ratio
    ratios = list(timbre.matched_tuning)
    n_steps = len(ratios) - 1 if abs(ratios[0] - 1.0) < 1e-9 else len(ratios)

    kbm = export_kbm(
        kbm_path,
        n_scale_steps=max(n_steps, 1),
        middle_note=middle_note,
        reference_note=reference_note,
        reference_freq=reference_freq,
    )
    return {"scl": scl, "kbm": kbm}
