"""Tests for :mod:`biotuner.mos.plotting`.

Figures are hard to assert on, so these check the things that actually go wrong
in plotting code: wrong number of drawn elements, silently dropped overlays,
axes limits that hide data, and crashes on edge-case inputs. The labyrinth's
geometry is checked against the theory layer rather than eyeballed.
"""

import math
from dataclasses import replace

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pytest
from matplotlib.colors import to_rgba

from biotuner.mos import plotting as P
from biotuner.mos import theory as T
from biotuner.mos.derive import best_mos, forward_scales, trajectory_from_windows
from biotuner.mos.scale import MOSScale

FIFTH = 3 / 2
#: S001, eyes closed -- the four alpha-band peaks in Hz that the forward and
#: inverse directions disagree about.
EEG_PEAKS = [10.07, 15.64, 19.31, 22.91]


@pytest.fixture(autouse=True)
def _close_figures():
    yield
    plt.close("all")


# --------------------------------------------------------------------------- #
# The labyrinth
# --------------------------------------------------------------------------- #
def test_labyrinth_draws_every_ring():
    fig, ax = P.plot_labyrinth(12)
    assert ax.name == "polar"
    assert ax.get_ylim()[1] > 12
    # Every MOS cardinality from 2 to 12 must appear as a radius somewhere.
    radii = set()
    for line in ax.get_lines():
        radii.update(np.round(line.get_ydata(), 6))
    for card in range(2, 13):
        assert float(card) in radii, f"ring {card} missing"


def test_labyrinth_is_left_right_symmetric():
    """Milne et al. section 4: 'the structure is left-right symmetric, because a
    scale created using any generator is identical to the scale generated by the
    complement of the generator'."""
    nodes = T.sb_tree_nodes(14)
    values = {float(n.node) for n in nodes}
    for v in values:
        assert any(abs((1.0 - v) - w) < 1e-12 for w in values)


def test_spokes_stop_on_their_own_ring():
    """'For each spoke, there is some circle that the spoke touches but does not
    cross. This circle gives the number of notes in the corresponding equal step
    scale.'"""
    for node in T.sb_tree_nodes(14):
        assert node.cardinality == node.node.denominator


def test_labyrinth_zoom_restricts_the_angular_window():
    fig, ax = P.plot_labyrinth(9, generator_range=(0.5, 0.65))
    assert ax.get_thetamin() == pytest.approx(180.0)
    assert ax.get_thetamax() == pytest.approx(234.0)


def test_labyrinth_overlays_peaks_and_highlight():
    scale = MOSScale.from_signature(5, 2, tuning=31)
    plain, _ = P.plot_labyrinth(12)
    n_plain = len(plain.axes[0].get_lines())
    plt.close(plain)
    fig, ax = P.plot_labyrinth(
        12, peaks=[1.0, 1.125, 1.5], peak_weights=[1.0, 0.5, 0.2], highlight=scale
    )
    assert len(ax.get_lines()) > n_plain
    assert len(ax.collections) >= 1     # the peak scatter


def test_labyrinth_accepts_several_highlights():
    fig, ax = P.plot_labyrinth(12, highlight=[math.log2(1.5), math.log2(1.25)])
    assert ax is not None


def test_labyrinth_label_modes():
    for label in ("cents", "fraction", "none"):
        fig, ax = P.plot_labyrinth(7, label=label)
        assert (len(ax.get_xticks()) == 0) == (label == "none")
        plt.close(fig)


@pytest.mark.parametrize("n", [1, 2, 3, 4, 6])
def test_fractional_period_shows_only_multiples_of_n(n):
    """A scale with n periods per octave repeats n times, so a ring can only
    hold a note count divisible by n."""
    fig, ax = P.plot_labyrinth(24, periods_per_octave=n)
    radii = set()
    for line in ax.get_lines():
        radii.update(np.round(line.get_ydata(), 6))
    rings = sorted(r for r in radii if 0 < r <= 24)
    assert rings, "no rings drawn"
    assert all(int(round(r)) % n == 0 for r in rings)


def test_fractional_period_has_n_fold_rotational_symmetry():
    """Every arc appears once per period, at a fixed angular offset."""
    n = 3
    fig, ax = P.plot_labyrinth(24, periods_per_octave=n)
    inner = [ln for ln in ax.get_lines()
             if len(ln.get_ydata()) > 8 and abs(ln.get_ydata()[0] - 6.0) < 1e-9]
    starts = sorted(float(ln.get_xdata()[0]) % (2 * math.pi) for ln in inner)
    assert len(starts) % n == 0
    # Rotating the whole set by one period maps it onto itself.
    shifted = sorted((s + 2 * math.pi / n) % (2 * math.pi) for s in starts)
    assert np.allclose(starts, shifted, atol=1e-6)


def test_fractional_period_defaults_to_the_ordinary_labyrinth():
    a, ax_a = P.plot_labyrinth(18)
    b, ax_b = P.plot_labyrinth(18, periods_per_octave=1)
    assert len(ax_a.get_lines()) == len(ax_b.get_lines())


def test_fractional_period_validates():
    with pytest.raises(ValueError, match="periods_per_octave must be at least 1"):
        P.plot_labyrinth(12, periods_per_octave=0)
    with pytest.raises(ValueError, match="notes per period"):
        P.plot_labyrinth(6, periods_per_octave=5)


def test_labyrinth_rejects_a_bad_label():
    with pytest.raises(ValueError, match="label must be"):
        P.plot_labyrinth(7, label="hertz")


def test_labyrinth_rejects_a_degenerate_ring_count():
    with pytest.raises(ValueError, match="at least 2"):
        P.plot_labyrinth(1)


def test_labyrinth_rejects_a_cartesian_axes():
    fig, ax = plt.subplots()
    with pytest.raises(ValueError, match="needs a polar axes"):
        P.plot_labyrinth(7, ax=ax)


def test_labyrinth_honours_a_pseudo_octave_in_its_labels():
    fig, ax = P.plot_labyrinth(7, period=3.0, label="cents")
    labels = [t.get_text() for t in ax.get_xticklabels() if t.get_text()]
    # A 3/1 period is 1902 cents, so the labels must run well past 1200.
    assert max(float(x) for x in labels) > 1200


def test_temperament_overlay_does_not_crash_the_plot():
    fig, ax = P.plot_labyrinth(12, temperaments=True)
    assert ax is not None


# --------------------------------------------------------------------------- #
# Tree
# --------------------------------------------------------------------------- #
def test_stern_brocot_plots_one_marker_per_node():
    fig, ax = P.plot_stern_brocot(12)
    n_nodes = len(T.sb_tree_nodes(12))
    markers = [ln for ln in ax.get_lines() if ln.get_marker() == "o"]
    assert len(markers) == n_nodes


def test_stern_brocot_highlights_a_generator_path():
    fig, ax = P.plot_stern_brocot(12, highlight_generator=math.log2(FIFTH))
    texts = {t.get_text() for t in ax.texts}
    for frac in ("1/2", "2/3", "3/5", "4/7", "7/12"):
        assert frac in texts


def test_stern_brocot_parent_lookup_is_consistent():
    for node in T.sb_tree_nodes(16):
        parent = P._sb_parent(node)
        if parent is None:
            assert node.node.denominator == 2      # only the root 1/2
        else:
            assert parent in (node.left, node.right)


# --------------------------------------------------------------------------- #
# One scale
# --------------------------------------------------------------------------- #
def test_scale_wheel_draws_one_wedge_per_degree():
    scale = MOSScale.from_signature(5, 2, tuning=31)
    fig, ax = P.plot_scale_wheel(scale)
    assert len(ax.patches) == scale.cardinality


def test_scale_wheel_accepts_a_mode():
    mode = MOSScale.from_signature(5, 2, tuning=12).mode(1)
    fig, ax = P.plot_scale_wheel(mode)
    assert "Ionian" in ax.get_title()


def test_step_covariation_crosses_at_the_equalized_landmark():
    fig, axes = P.plot_step_covariation(5, 2)
    top = axes[0]
    large, small = top.get_lines()[0], top.get_lines()[1]
    xl, yl = large.get_xdata(), large.get_ydata()
    ys = small.get_ydata()
    eq = float(T.mos_landmarks(5, 2).equalized) * 1200
    i = int(np.argmin(np.abs(xl - eq)))
    assert yl[i] == pytest.approx(ys[i], abs=1.0)

    # The plot deliberately spans the MOS *and* its inverse, meeting at the
    # equalized landmark, so the tiling identity swaps counts across it:
    # 5L + 2s above, 2L + 5s below.
    above, below = xl > eq, xl < eq
    assert np.allclose(5 * yl[above] + 2 * ys[above], 1200.0, atol=1e-6)
    assert np.allclose(2 * yl[below] + 5 * ys[below], 1200.0, atol=1e-6)


def test_step_covariation_marks_a_chosen_tuning():
    scale = MOSScale.from_signature(5, 2, tuning=31)
    fig, axes = P.plot_step_covariation(5, 2, mark=scale.generator)
    assert fig is not None


def test_modes_plot_has_one_row_per_mode():
    scale = MOSScale.from_signature(5, 2, tuning=12)
    fig, ax = P.plot_modes(scale)
    assert len(ax.get_yticks()) == scale.cardinality
    assert len(ax.patches) == scale.cardinality**2
    assert [t.get_text() for t in ax.get_yticklabels()][0] == "Locrian"


def test_mode_lattice_has_two_panels():
    scale = MOSScale.from_signature(5, 2, tuning=12)
    fig, axes = P.plot_mode_lattice(scale, width=3, height=2)
    assert len(axes) == 2
    names = {t.get_text() for t in axes[0].texts}
    assert "Lydian" in names and "Dorian" in names


def test_family_plot_lists_every_member():
    fig, ax = P.plot_mos_family(FIFTH, max_cardinality=17)
    labels = [t.get_text() for t in ax.get_yticklabels()]
    assert len(labels) == 5
    assert "5L2s  (7)" in labels


def test_family_plot_rejects_a_generator_with_no_family():
    with pytest.raises(ValueError, match="no MOS at or below"):
        P.plot_mos_family(FIFTH, max_cardinality=2)


# --------------------------------------------------------------------------- #
# Fits and trajectories
# --------------------------------------------------------------------------- #
def test_fit_plot_marks_used_and_unused_degrees():
    ratios = [1.0, 1.13, 1.26, 1.34, 1.49]
    fit = best_mos(ratios, max_cardinality=12)
    fig, axes = P.plot_mos_fit(fit, ratios)
    assert len(axes) == 2
    assert f"{fit.error_cents:.2f}" in axes[0].get_title()


def test_fit_plot_works_without_the_raw_ratios():
    ratios = [1.0, 1.13, 1.26, 1.34, 1.49]
    fig, axes = P.plot_mos_fit(best_mos(ratios, max_cardinality=12))
    assert axes[0] is not None


def test_trajectory_plot_draws_a_path_and_time_series():
    a = MOSScale.from_signature(5, 2, tuning=12).ratios
    b = MOSScale.from_signature(4, 3, tuning=19).ratios
    traj = trajectory_from_windows([a, a, b, b, a], max_cardinality=12)
    fig, axes = P.plot_mos_trajectory(traj)
    assert len(axes) == 4          # labyrinth + three time series
    assert axes[0].name == "polar"


def test_trajectory_plot_survives_gaps():
    a = MOSScale.from_signature(5, 2, tuning=12).ratios
    traj = trajectory_from_windows([a, [], a], max_cardinality=12)
    fig, axes = P.plot_mos_trajectory(traj)
    assert axes[0] is not None


def test_trajectory_plot_needs_at_least_one_fit():
    with pytest.raises(ValueError, match="no successful fits"):
        P.plot_mos_trajectory([None, None])


# --------------------------------------------------------------------------- #
# Forward vs inverse
# --------------------------------------------------------------------------- #
def _eeg_readings(**kwargs):
    kwargs.setdefault("include_ratios", False)     # raw Hz: 19.31 is no interval
    kwargs.setdefault("min_cardinality", 5)
    kwargs.setdefault("max_cardinality", 9)
    return forward_scales(EEG_PEAKS, **kwargs)[:6]


def _forward_scatter(ax):
    return ax.collections[-1]


def _stars(ax):
    return [ln for ln in ax.get_lines() if ln.get_marker() == "*"]


def test_forward_vs_inverse_plots_one_point_per_reading():
    readings = _eeg_readings()
    fig, ax = P.plot_forward_vs_inverse(readings, best_mos(EEG_PEAKS,
                                                           max_cardinality=9))
    assert ax.name == "polar"
    offsets = _forward_scatter(ax).get_offsets()
    assert len(offsets) == len(readings)
    # Angle is the generator, radius the cardinality -- the labyrinth's own axes.
    drawn = {(round(float(t) / (2 * math.pi), 9), int(round(r)))
             for t, r in offsets}
    expected = {(round(P._bright(r.scale.generator), 9), r.scale.cardinality)
                for r in readings}
    assert drawn == expected


def test_forward_vs_inverse_marks_the_two_directions_apart():
    """The figure exists to tell an observed generator from a latent one, so
    the two must not be drawn as the same kind of thing."""
    readings = _eeg_readings()
    inverse = best_mos(EEG_PEAKS, max_cardinality=9)
    fig, ax = P.plot_forward_vs_inverse(readings, inverse)

    stars = _stars(ax)
    assert len(stars) == 1, "exactly one inverse fit, and only it is a star"
    star = stars[0]
    assert star.get_markeredgecolor() == P.INVERSE_COLOR
    # Open, so a forward reading landing on the same spot still shows through.
    assert str(star.get_markerfacecolor()).lower() == "none"
    assert star.get_ydata()[0] == inverse.scale.cardinality
    assert star.get_xdata()[0] == pytest.approx(
        2 * math.pi * P._bright(inverse.scale.generator)
    )

    # The inverse fit is not smuggled into the forward scatter, and no forward
    # marker can borrow its colour: the ramp and the flag are disjoint.
    scatter = _forward_scatter(ax)
    assert len(scatter.get_offsets()) == len(readings)
    shades = scatter.get_cmap()(scatter.norm(scatter.get_array()))
    assert not any(np.allclose(shade, to_rgba(P.INVERSE_COLOR), atol=0.05)
                   for shade in shades)

    labels = [t.get_text() for t in ax.get_legend().get_texts()]
    assert sum("inverse fit" in label for label in labels) == 1
    assert len(labels) > 1, "the forward readings need their own key"


def test_forward_vs_inverse_sizes_points_by_corroboration():
    """A stack of fifths states the fifth twice -- 3/2, and 27/16 over 9/8 --
    so that generator is better attested than the ones seen once."""
    readings = forward_scales([1.0, 1.125, 1.265625, 1.5], max_cardinality=12)
    readings = sorted(readings, key=lambda r: r._rank_key)[:8]
    counts = [r.n_sources for r in readings]
    assert len(set(counts)) > 1, "fixture must exercise the size encoding"

    fig, ax = P.plot_forward_vs_inverse(readings)
    sizes = _forward_scatter(ax).get_sizes()
    assert sizes[counts.index(max(counts))] > sizes[counts.index(min(counts))]


def test_forward_vs_inverse_draws_the_bright_half_only():
    """Neither direction can report the dark spelling, and a permanently empty
    half-circle would read as absence of evidence."""
    fig, ax = P.plot_forward_vs_inverse(_eeg_readings())
    assert ax.get_thetamin() == pytest.approx(180.0)
    assert ax.get_thetamax() == pytest.approx(360.0)
    thetas = [float(t) for t, _ in _forward_scatter(ax).get_offsets()]
    thetas.append(float(_stars(ax)[0].get_xdata()[0]))
    assert all(math.pi <= t <= 2 * math.pi + 1e-9 for t in thetas)


def test_forward_vs_inverse_captions_the_generator_it_drew():
    """A fit is free to name either spelling of its own scale.  The star goes to
    the bright one, so the caption has to as well."""
    fit = best_mos(EEG_PEAKS, max_cardinality=9)
    bright = P._bright(fit.scale.generator)
    dark = MOSScale(fit.scale.n_large, fit.scale.n_small, 1.0 - bright,
                    fit.scale.period, validate=False)
    fig, ax = P.plot_forward_vs_inverse(_eeg_readings(), replace(fit, scale=dark))

    assert _stars(ax)[0].get_xdata()[0] == pytest.approx(2 * math.pi * bright)
    assert f"{bright * 1200:.1f} c" in ax.get_title()
    assert f"{(1 - bright) * 1200:.1f} c" not in ax.get_title()


def test_forward_vs_inverse_keys_each_generator_once():
    readings = _eeg_readings()
    fig, ax = P.plot_forward_vs_inverse(readings)
    n_generators = len({round(P._bright(r.scale.generator), 9) for r in readings})
    tags = sorted(t.get_text() for t in ax.texts)
    assert tags == sorted(P._tag_label(i) for i in range(n_generators))
    labels = [t.get_text() for t in ax.get_legend().get_texts()]
    assert sum(any(label.startswith(tag) for tag in tags) for label in labels) \
        == n_generators


def test_forward_vs_inverse_derives_the_inverse_from_the_same_targets():
    readings = _eeg_readings()
    fig, ax = P.plot_forward_vs_inverse(readings)
    expected = best_mos(
        list(readings[0].fit.targets),
        max_cardinality=max(r.scale.cardinality for r in readings),
    )
    assert f"inverse {expected.signature}" in ax.get_title()
    assert len(_stars(ax)) == 1


def test_forward_vs_inverse_leaves_the_callers_list_alone():
    readings = _eeg_readings()
    order = [id(r) for r in readings]
    P.plot_forward_vs_inverse(readings, top_n=3)
    assert [id(r) for r in readings] == order


def test_forward_vs_inverse_needs_a_reading():
    with pytest.raises(ValueError, match="no forward readings"):
        P.plot_forward_vs_inverse([])


def test_forward_vs_inverse_rejects_something_that_is_not_a_fit():
    with pytest.raises(TypeError, match="must be a MOSFit"):
        P.plot_forward_vs_inverse(_eeg_readings(), 0.5)


def test_forward_vs_inverse_accepts_a_single_reading_and_a_shared_axes():
    fig = plt.figure(figsize=(7, 7))
    polar = fig.add_subplot(1, 1, 1, projection="polar")
    out_fig, out_ax = P.plot_forward_vs_inverse(_eeg_readings()[0], ax=polar,
                                                annotate=False)
    assert out_ax is polar and out_fig is fig
    assert len(_forward_scatter(out_ax).get_offsets()) == 1
    assert len(out_ax.texts) == 0        # annotate=False drops the rim tags


# --------------------------------------------------------------------------- #
# JI landscape
# --------------------------------------------------------------------------- #
def test_ji_landscape_is_blank_where_no_mos_exists():
    fig, ax = P.plot_ji_landscape(max_cardinality=10, resolution=120)
    heat = ax.images[0].get_array()
    assert np.ma.is_masked(heat) or np.isnan(np.asarray(heat)).any()


def test_ji_landscape_finds_the_known_optimum_for_twelve_notes():
    """12 notes approximate 5-limit best near a 702-cent generator."""
    targets = P.JI_5_LIMIT
    tpos = np.mod(np.log2(np.asarray(targets)), 1.0)
    best_err, best_g = 1e9, None
    for g in np.linspace(0.5, 1.0, 4001)[1:-1]:
        cards = [c for c, _, _ in T.mos_series(g, 12, include_trivial=True)]
        if 12 not in cards:
            continue
        deg = np.asarray(T.degrees_from_generator(float(g), 12))
        d = np.abs(tpos[:, None] - deg[None, :])
        d = np.minimum(d, 1 - d)
        err = float(d.min(axis=1).mean() * 1200)
        if err < best_err:
            best_err, best_g = err, g
    assert best_g * 1200 == pytest.approx(701.7, abs=2.0)
    assert best_err == pytest.approx(8.4, abs=0.5)


def test_ji_landscape_colour_ceiling_is_applied():
    fig, ax = P.plot_ji_landscape(max_cardinality=8, resolution=100,
                                  max_error_cents=25.0)
    assert ax.images[0].get_clim() == (0.0, 25.0)


# --------------------------------------------------------------------------- #
# Fourier play states
# --------------------------------------------------------------------------- #
def test_play_state_plot_shows_the_spectrum():
    from biotuner.mos.fourier import partial

    scale = MOSScale.from_signature(5, 2, tuning=12)
    fig, axes = P.plot_play_state(partial(7, 1), scale)
    assert len(axes) == 2
    assert axes[0].name == "polar"
    assert len(axes[1].patches) == 7
