name: Build and Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history

      - name: Delete and recreate docs_build branch
        run: |
          git fetch origin main
          git checkout main
          git push origin --delete docs_build || true  # Delete existing docs_build branch
          git checkout -b docs_build
          git push origin docs_build  # Recreate docs_build from main

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build Sphinx documentation
        run: |
          sphinx-build -b html docs docs/_build/html

      - name: Disable Jekyll
        run: touch docs/_build/html/.nojekyll

      - name: Deploy to docs_build branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT_TOKEN }}
          publish_branch: docs_build
          publish_dir: docs/_build/html
