name: Build and Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to allow branch manipulation

      - name: Mirror main to docs_build
        run: |
          git fetch origin main
          git checkout main
          git push origin main:docs_build --force  # Copy entire main branch to docs_build

      - name: Check out docs_build branch
        uses: actions/checkout@v3
        with:
          ref: docs_build
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build Sphinx documentation
        working-directory: docs
        run: |
          sphinx-build -b html . _build/html

      - name: Check build output
        run: ls -la docs/_build/html  # Verify the built docs

      - name: Deploy to docs_build branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT_TOKEN }}
          publish_branch: docs_build
          publish_dir: docs/_build/html  # Only deploy built docs
          keep_files: true               # Keep the rest of the repo intact
