name: Build and Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror main to docs_build
        run: |
          git fetch origin main
          git checkout main
          git checkout -B docs_build

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build Sphinx documentation
        run: |
          sphinx-build -b html docs docs/_build/html

      - name: Deploy docs
        run: |
          rsync -a --delete docs/_build/html/ docs/  # Copy built docs to /docs

      - name: Debug Sphinx Build Output
        run: |
          echo "Listing built docs:"
          ls -R docs

      - name: Commit and push built docs
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git add docs
          git commit -m "Deploy updated documentation"
          git push https://x-access-token:${PAT_TOKEN}@github.com/your-username/your-repo.git docs_build --force


