name: Build and Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build Sphinx documentation
        run: |
          cd docs
          sphinx-build -b html . _build/html

      - name: Deploy to docs_build branch
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          cd docs/_build/html
          git init
          git config user.name "GitHub Actions"
          git config user.email "[email protected]"
          git add .
          git commit -m "Deploy updated documentation"
          git push --force "https://${PAT_TOKEN}@github.com/${{ github.repository }}.git" master:docs_build
