name: Build and Deploy Docs

on:
  push:
    branches:
      - docs_build
    paths:
      - 'docs/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror main to docs_build
        run: |
          git fetch origin main
          git checkout main
          git checkout -B docs_build

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build Sphinx documentation in /docs
        run: |
          sphinx-build -b html docs docs

      - name: Debug Sphinx Build Output
        run: |
          echo "Listing built docs:"
          ls -R docs

      - name: Commit and push built docs
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-github-username"
          git add docs
          git commit -m "Deploy updated documentation"
          git push origin docs_build --force
