name: Biotuner Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for accurate coverage reports

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov  # Ensure pytest-cov is installed
          pip install -r requirements.txt
          pip install .

      - name: Run tests with coverage
        run: |
          pytest --cov=biotuner --cov-branch --cov-report=xml --junitxml=test-reports/test-results-${{ matrix.python-version }}.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: test-reports/test-results-${{ matrix.python-version }}.xml

      - name: Upload coverage to Codecov
        if: success()  # Upload only if tests pass
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: AntoineBellemare/biotuner
          file: coverage.xml
