name: Biotuner Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for accurate coverage tracking

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage
          pip install -r requirements.txt
          # IMPORTANT: Use editable install so coverage tracks files correctly
          pip install -e .

      - name: Run tests with coverage
        run: |
          pytest --cov=biotuner \
                 --cov-branch \
                 --cov-report=xml:coverage.xml \
                 --cov-report=term-missing \
                 --junitxml=test-reports/test-results-${{ matrix.python-version }}.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: test-reports/test-results-${{ matrix.python-version }}.xml

      - name: Debug Coverage File
        run: |
          echo ">>> Checking coverage.xml (first 50 lines) ..."
          head -n 50 coverage.xml
          echo ">>> Checking absolute paths in coverage.xml ..."
          grep "<source>" coverage.xml || echo "No source path found!"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Set this in GitHub Secrets
          slug: AntoineBellemare/biotuner
          files: coverage.xml
          fail_ci_if_error: true  # Fail if upload fails
          verbose: true  # Debugging
          root_dir: biotuner  # Ensure correct root directory
